<?
$menu['home/admin-book']['name'] = 'Книга';
$menu['home/admin-book']['action'] = 'edit';
$menu['home/admin-avtor']['name'] = 'Авторы';
$menu['home/admin-avtor']['action'] = 'edit';
$menu['home/admin-serii']['name'] = 'Серии';
$menu['home/admin-serii']['action'] = 'edit';
$menu['home/admin-translit']['name'] = 'Переводчики';
$menu['home/admin-translit']['action'] = 'edit';
$menu['home/admin-soder']['name'] = 'Содержание';
$menu['home/admin-soder']['action'] = 'edit';
$menu['home/admin-text']['name'] = 'Текст';
$menu['home/admin-text']['action'] = 'edit';
$menu['home/admin-files']['name'] = 'Файлы';
$menu['home/admin-files']['action'] = 'edit';
?>

<nav class="navbar navbar-default" role="navigation">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <?foreach($menu as $k => $v):?>
                <?
                $class = ' class="" ';
                if($route == $k)$class = ' class="active" ';
                ?>
                <?
                $params['action'] = $v['action'];
                $params['id'] = $book_id;
                ?>
                <li <?=$class;?>><a href="<?=$this->url($k, $params)?>"><?=$v['name'];?></a></li>
            <?endforeach;?>
        </ul>
    </div>
</nav>