<table   id="table_id_pere">
	<thead>
	<th>№</th>
	<th>Имя</th>
	<th>Email</th>
	<th>Phone</th>
	<th>Дата</th>
	<th>Действие</th>
	</thead>
	</thead>
	<tbody>
	<? foreach ($payUser as $v): ?>
		<tr>
			<td><?= $v->id_pay_user; ?></td>
			<td><?= $v->name_pay_user; ?></td>
			<td><?= $v->email_pay_user; ?></td>
			<td><?= $v->phone_pay_user; ?></td>
			<td><?= date("d.m.Y H:i",strtotime($v->datetime_pay_user)); ?></td>
			<td>
				<a title="Редактировать" href="/pay/redactorPay/<?= $v->id_pay_user; ?>"><i class="icon-edit"></i>
				<a title="Удалить"  onclick = "if(!confirm('Удалить?')) return false;"   href="/pay/deletePay/<?= $v->id_pay_user; ?>"><i class="icon-remove"></i>
			</td>
		</tr>
	<? endforeach; ?>
	</tbody>
</table>
</form>
<script>
	$(function(){
			$.extend($.tablesorter.themes.bootstrap, {
				table: 'table table-bordered',
				header: 'bootstrap-header'// give the header a gradient background
			});
			$("#table_id_pere").tablesorter({
				theme: "bootstrap",
				widthFixed : true,
				showProcessing: true,
				headerTemplate : '{content} {icon}',
				widgets: [ 'uitheme', 'zebra', 'filter']
			});

		}
	)
</script>

