<?php echo $this->partial('application/menu/admin-book'); ?>
<?php
$title = 'Добавить ad';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<a class="btn btn-info btn-sm margin-bootom"
   href="<?= $this->url(
       'home/admin-ad',
       ['action' => 'index']
   ); ?>">
    Список ad
</a>

<?php
echo $this->flashMessenger()->render();
?>

<?php $this->form->prepare(); ?>
<?= $this->form()->openTag($this->form) ?>
<?php foreach ($this->form as $elementOrFieldset): ?>
    <div class = "row container-fluid">
        <?php if ($elementOrFieldset instanceof Zend\Form\Fieldset): ?>
            <?= $this->formCollection($elementOrFieldset) ?>
        <?php else: ?>
            <?= $this->formRow($elementOrFieldset) ?>
        <?php endif; ?>
    </div>
<?php endforeach; ?>
