<?php
echo $this->partial('application/menu/admin-book',
    [
        'book_id' => $id,
        'route' => 'home/admin-book'
    ]
);
?>

<?php
$title = 'Добавить книгу';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php $this->form->prepare(); ?>
<?= $this->form()->openTag($this->form) ?>
<?php foreach ($this->form as $elementOrFieldset): ?>
    <div class = "row">
        <?php if ($elementOrFieldset instanceof Zend\Form\Fieldset): ?>
            <?= $this->formCollection($elementOrFieldset) ?>
        <?php else: ?>
            <?= $this->formRow($elementOrFieldset) ?>
        <?php endif; ?>
    </div>
<?php endforeach; ?>


<link rel="stylesheet" href="/assets/js/wysihtml5/bootstrap-wysihtml5.css">
<script src="/assets/js/wysihtml5/wysihtml5-0.4.0pre.min.js"></script>
<script src="/assets/js/wysihtml5/bootstrap-wysihtml5.js"></script>

<link rel="stylesheet" href="/assets/js/select2/select2.css"
      id="style-resource-3">
<script src="/assets/js/select2/select2.min.js"
        id="script-resource-11"></script>
<script src="/assets/js/bootstrap-switch.min.js"
        id="script-resource-8"></script>


<script>
    $( function() {
        function log( message ) {
            $( "<div>" ).text( message ).prependTo( "#log" );
            $( "#log" ).scrollTop( 0 );
        }

        $( "form#book input[type=text].autosearch" ).autocomplete({
            source: function( request, response ) {

                name = this.element.attr('data-name');

                $.ajax( {
                    url: "/ajaxsearch/",
                    dataType: "json",
                    data: {
                        term : {name: name,
                            value: request.term,
                        }
                    },
                    success: function( data ) {
                        response( data );
                    }
                } );
            },
            minLength: 2,
            select: function( event, ui ) {
                log( "Selected: " + ui.item.value + " aka " + ui.item.id );
            }
        } );
    } );
</script>
