<?php echo $this->partial('application/menu/admin-book'); ?>
<?php
$title = 'Добавить книгу';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php

$form->setAttribute('action', $this->url('home/admin-book', ['action' => 'add']));
echo $this->ztbForm($this->form);
?>


<link rel="stylesheet" href="/assets/js/wysihtml5/bootstrap-wysihtml5.css">
<script src="/assets/js/wysihtml5/wysihtml5-0.4.0pre.min.js"></script>
<script src="/assets/js/wysihtml5/bootstrap-wysihtml5.js"></script>

<link rel="stylesheet" href="/assets/js/select2/select2.css"
      id="style-resource-3">
<script src="/assets/js/select2/select2.min.js"
        id="script-resource-11"></script>
<script src="/assets/js/bootstrap-switch.min.js"
        id="script-resource-8"></script>



