<?php
echo $this->partial('application/menu/admin-book',
    [
        'book_id' => $book->getId(),
        'route' => 'home/admin-book'
    ]
);
?>

<?php
/** @var \Application\Entity\Book $book */
$title = 'Редактировать книгу';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<a class = "btn btn-red glyphicon-remove-circle" href="<?= $this->url(
    'home/admin-book',
    [
        'action' => 'delete',
        'id'     => $book->getId(),
    ]
) ?>
                    ">
    Удалить
</a>

<div class = "text-right">
    <a href = "<?=$this->url('home/genre/one/book',
        [
                'book' => $book->getAlias(),
                'alias_menu' => $book->getNAliasMenu(),
                's' => $book->getNS()
        ])
    ;?>">
        <?=$book->getName();?>
    </a>
</div>
<?php $this->form->prepare(); ?>
<?= $this->form()->openTag($this->form) ?>
<?php foreach ($this->form as $elementOrFieldset): ?>
    <div class = "row">
        <?php if ($elementOrFieldset instanceof Zend\Form\Fieldset): ?>
            <?= $this->formCollection($elementOrFieldset) ?>
        <?php else: ?>
            <?= $this->formRow($elementOrFieldset) ?>
        <?php endif; ?>
    </div>
<?php endforeach; ?>
<img class = "img-size" src = "/templates/newimg/small/<?=$form->get('foto')->getValue();?>">
<link rel="stylesheet" href="/assets/js/wysihtml5/bootstrap-wysihtml5.css">
<script src="/assets/js/wysihtml5/wysihtml5-0.4.0pre.min.js"></script>
<script src="/assets/js/wysihtml5/bootstrap-wysihtml5.js"></script>
<link rel="stylesheet" href="/assets/js/select2/select2.css"
      id="style-resource-3">
<script src="/assets/js/select2/select2.min.js"
        id="script-resource-11"></script>
<script src="/assets/js/bootstrap-switch.min.js"
        id="script-resource-8"></script>

<script>
    $( function() {

        $('body').on('click', '.glyphicon-remove-circle', function(){
            if (confirm("Вы действительно хотите удалить книгу?")) {
                return true;
            }
            return false;
        })

        function log( message ) {
            $( "<div>" ).text( message ).prependTo( "#log" );
            $( "#log" ).scrollTop( 0 );
        }

        $( "form#book input[type=text].autosearch" ).autocomplete({
            source: function( request, response ) {

                name = this.element.attr('name');

                $.ajax( {
                    url: "/ajaxsearch/",
                    dataType: "json",
                    data: {
                        term : {name: name,
                            value: request.term,
                        }
                    },
                    success: function( data ) {
                        response( data );
                    }
                } );
            },
            minLength: 2,
            select: function( event, ui ) {
                log( "Selected: " + ui.item.value + " aka " + ui.item.id );
            }
        } );
    } );
</script>