<?php echo $this->partial('application/menu/admin-book'); ?>
<?php
/** @var \Application\Entity\Book $book */
$title = 'Редактировать книгу';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class = "text-right">
    <a href = "<?=$this->url('home/genre/one/book',
        [
                'book' => $book->getAlias(),
                'alias_menu' => $book->getNAliasMenu(),
                's' => $book->getNS()
        ])
    ;?>">
        <?=$book->getName();?>
    </a>
</div>
<?php

$form->setAttribute(
    'action',
    $this->url(
        'home/admin-book',
        [
            'action' => 'edit',
            'id'     => $book->getId(),
        ]
    )
);
echo $this->ztbForm($this->form);
?>
<img class = "img-size" src = "/templates/newimg/original/<?=$form->get('foto')->getValue();?>">

<link rel="stylesheet" href="/assets/js/wysihtml5/bootstrap-wysihtml5.css">
<script src="/assets/js/wysihtml5/wysihtml5-0.4.0pre.min.js"></script>
<script src="/assets/js/wysihtml5/bootstrap-wysihtml5.js"></script>

<link rel="stylesheet" href="/assets/js/select2/select2.css"
      id="style-resource-3">
<script src="/assets/js/select2/select2.min.js"
        id="script-resource-11"></script>
<script src="/assets/js/bootstrap-switch.min.js"
        id="script-resource-8"></script>

<script>
    $( function() {
        function log( message ) {
            $( "<div>" ).text( message ).prependTo( "#log" );
            $( "#log" ).scrollTop( 0 );
        }

        $( "form#book input[type=text].autosearch" ).autocomplete({
            source: function( request, response ) {

                name = this.element.attr('name');

                $.ajax( {
                    url: "/ajaxsearch/",
                    dataType: "json",
                    data: {
                        term : {name: name,
                            value: request.term,
                        }
                    },
                    success: function( data ) {
                        response( data );
                    }
                } );
            },
            minLength: 2,
            select: function( event, ui ) {
                log( "Selected: " + ui.item.value + " aka " + ui.item.id );
            }
        } );
    } );
</script>