<? foreach ($typeField as $v): ?>
    <table class="table table-striped table-bordered table-hover typetable">
        <thead>
        <th>Название</th>
        <th>Значение</th>
        </thead>
        <tbody>
        <tr>
            <td><?= $v['name_type_field'] ?>:</td>
            <td>
                <?= $v['gen_field'] ?>
            </td>
        </tr>
        </tbody>
    </table>
<? endforeach; ?>


 