<?if($categoryBrand -> count() != 0):?>
<table   class="table table-striped table-bordered table-hover typetable">
	<thead>
	<th>Название</th>
	<th>Значение</th>
	</thead>
	<tbody>


	<?foreach($categoryBrand as $g):?>
		<tr>
			<td><?=$g -> name_category;?></td>
			<td><input class = "integer" value="<?=$g->money_cb;?>" type="text" name="money_cb[<?=$g -> id_cb?>]" /></td>
		</tr>
	<?endforeach?>

	</tbody>
</table>
	<?else:?>
	<b>Категорий нет</b>
<?endif;?>
