<?php echo $this->partial('application/menu/admin-book'); ?>
<?php
$title = 'Добавить книгу';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<a class="btn btn-info btn-sm margin-bootom"
   href="<?= $this->url(
       'home/admin-fb',
       ['action' => 'index']
   ); ?>">
    Список файлов
</a>

<?php

$form->setAttribute('action', $this->url('home/admin-fb', ['action' => 'add']));
echo $this->ztbForm($this->form);
?>


