
<?php
$title = 'Добавить книгу';
$this->headTitle($title);
?>
<h1>Тест</h1>


<?php
echo $this->flashMessenger()->render();
?>

<?php $this->form->prepare(); ?>
<?= $this->form()->openTag($this->form) ?>
<?php foreach ($this->form as $elementOrFieldset): ?>
    <div class = "row container-fluid">
        <?php if ($elementOrFieldset instanceof Zend\Form\Fieldset): ?>
            <?= $this->formCollection($elementOrFieldset) ?>
        <?php else: ?>
            <?= $this->formRow($elementOrFieldset) ?>
        <?php endif; ?>
    </div>
<?php endforeach; ?>
