<!--Вспомогательный блок-->
<div id="help">
    <table class="table table-striped table-bordered table-hover typetable">
        <thead>
        <th>Название</th>
		<th>Alias</th>
        <th>Значение</th>
		<th>Раздел</th>
        <th>Показывать в фильтре</th>
        <th>Показывать в карточке</th>
        <th>Сортировка</th>
        <th>Операции</th>
        </thead>
        <tbody>
        <tr>
			<td>
				<input value="" name="name_type_field" type="text"
					   class="name_type_field"
					   placeholder="Название поля">
			</td>
			<td>
				<input value="" name="alias_type_field" type="text"
					   class="alias_type_field"
					   placeholder="Alias">
			</td>
            <td>
                <select name="id_field">
                    <? foreach ($field as $v): ?>
                        <option value="<?= $v->id_field; ?>"><?= $v->name_field; ?></option>
                    <? endforeach; ?>
                </select>
            </td>
			<td>
				<select name="id_section">
						<option value="0">Не выбран</option>
					<? foreach ($section as $v): ?>
						<option value="<?= $v->id_section; ?>"><?= $v->name_section; ?></option>
					<? endforeach; ?>
				</select>
			</td>
            <td style="text-align: center">
                <input name="vis_type_field" type="checkbox" />
            </td>
	        <td style="text-align: center">
		        <input name="vis2_type_field" type="checkbox" />
	        </td>
            <td>
                <input style="width:50px;" name="order_type_field" type="text" class="form-control" placeholder="Сортировка">
            </td>

            <td>
                <button onclick="template.del(this);return false;" class="btn">Удалить</button>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<!--Конец вспомогательного-->
<form id="template" action="" method="POST">
    <table class="table table-striped table-bordered table-hover table_form">
        <thead>
        <th>Название</th>
        <th>Значение</th>
        </thead>
        <tbody>
        <tr>
            <td>Шаблон:</td>
            <td><input name="name_type" type="text" class="form-control" placeholder="Название шаблона"/></td>
        </tr>
        <tr>
	        <td>Страницы сайта:</td>
	        <td><input name="site_content_type" type="checkbox" class="form-control"/></td>
        </tr>
        </tbody>
    </table>
    <div id="content_table"></div>
    <div class="button_block">
        <input type="button" value="Добавить поле" onclick="template.add(this,self);return false;" class="btn"/>
        <input class="btn" type="submit" value="Сохранить" name="send"/>
    </div>
</form>

<div class="clearfix"></div>

