<table   id="table_id_pere">
	<thead>
	<th>№</th>
	<th>Название</th>
	<th>Страницы сайта</th>
	<th>Дата и время</th>
	<th>События</th>
	</thead>
	</thead>
	<tbody>
	<? foreach ($type as $v): ?>
		<tr>
			<td><?= $v->id_type; ?></td>
			<td><?= $v->name_type; ?></td>
			<td><?= $v->site_content_type; ?></td>
			<td><?= date("d.m.Y H:i",strtotime($v->datetime_create)); ?></td>
			<td>
				<a title="Редактировать" href='/template/redactorTemplate/<?= $v->id_type; ?>'"><i class="icon-edit"></i>
				<a title="Удалить"  onclick = "if(!confirm('Удалить?')) return false;"   href="/template/deleteTemplate/<?= $v->id_type; ?>"><i class="icon-remove"></i>
			</td>
		</tr>
	<? endforeach; ?>
	</tbody>
</table>
</form>
<script>
	$(function(){
			$.extend($.tablesorter.themes.bootstrap, {
				table: 'table table-bordered',
				header: 'bootstrap-header'// give the header a gradient background
			});
			$("#table_id_pere").tablesorter({
				theme: "bootstrap",
				widthFixed : true,
				showProcessing: true,
				headerTemplate : '{content} {icon}',
				widgets: [ 'uitheme', 'zebra', 'filter']
			});

		}
	)
</script>

