<table   id="table_id_pere">
	<thead>
	<th>№</th>
	<th>Название</th>
	<th>Alias</th>
	<th>Сортировка</th>
	</thead>
	</thead>
	<tbody>
	<? foreach ($section as $v): ?>
		<tr onclick="location.href='/template/redactorSection/<?= $v->id_section; ?>'">
			<td><?= $v->id_section; ?></td>
			<td><?= $v->name_section; ?></td>
			<td><?= $v->alias_section; ?></td>
			<td><?= $v->order_section; ?></td>
		</tr>
	<? endforeach; ?>
	</tbody>
</table>
</form>
<script>
	$(function(){
			$.extend($.tablesorter.themes.bootstrap, {
				table: 'table table-bordered',
				header: 'bootstrap-header'// give the header a gradient background
			});
			$("#table_id_pere").tablesorter({
				theme: "bootstrap",
				widthFixed : true,
				showProcessing: true,
				headerTemplate : '{content} {icon}',
				widgets: [ 'uitheme', 'zebra', 'filter']
			});

		}
	)
</script>

