<h4>Редактировать раздел</h4>
<?echo $this->form()->openTag($form);?>
<table class="table table-striped table-bordered table-hover typetable">
    <thead>
    <th>Название</th>
    <th>Значение</th>
    </thead>
    <tbody>
    <tr>
        <td>Название:</td>
        <td>
            <?
            $form->get('name_section')->setValue("{$section->name_section}");
            echo $this->formInput($form->get('name_section'));
            echo $this->formElementErrors($form->get('name_section'));
            ?>
        </td>
    </tr>
    <tr>
        <td>Alias:</td>
        <td>
            <?
            $form->get('alias_section')->setValue("{$section->alias_section}");
            echo $this->formInput($form->get('alias_section'));
            echo $this->formElementErrors($form->get('alias_section'));
            ?>
        </td>
    </tr>
    <tr>
        <td>Сортировка:</td>
        <td>
            <?
            $form->get('order_section')->setValue("{$section->order_section}");
            echo $this->formInput($form->get('order_section'));
            echo $this->formElementErrors($form->get('order_section'));
            ?>
        </td>
    </tr>
    </tbody>
</table>
<div class="button_block">
<div id="button_id_block" class="btn-group">
    <?
    echo $this->formSubmit($form->get('send'));
    ?>
    <?
    echo $this->formSubmit($form->get('del'));
    ?>
</div>
</div>
<?php echo $this->form()->closeTag() ?>
