<div class="form-group"><label class="col-sm-3 control-label">Статус книги:</label>
    <div class="col-sm-5">
        <select id = "status-my-book" data-book_id = "<?=$id;?>" data-placeholder="Статус книги" name="test"
                class="selectboxit">
            <option value="0"
                    data-iconurl="/img/icons/adobe-air-icon.png">
                Не выбрано
            </option>
            <?foreach($status_all as $status):?>
                <?
                $selected = '';
                if($selected_status != null and $status->getStatusId() == $selected_status->getStatus()->getStatusId()){

                    $selected = " selected = 'selected' ";

                }?>
                <option <?=$selected;?> value="<?=$status->getStatusId();?>"
                        data-iconurl="/img/icons/<?=$status->getSrc();?>">
                    <?=$status->getName();?>
                </option>

            <?endforeach;?>
        </select>

    </div>
</div>

<link rel="stylesheet" href="/assets/js/selectboxit/jquery.selectBoxIt.css"
      id="style-resource-3">
<script src="/assets/js/selectboxit/jquery.selectBoxIt.min.js"
        id="script-resource-11"></script>
<script src="/assets/js/bootstrap-switch.min.js"
        id="script-resource-8"></script>
