<?echo $this->form()->openTag($form);?>
<table class="table table-striped table-bordered table-hover typetable">
    <thead>
    <th>Название</th>
    <th>Значение</th>
    </thead>
    <tbody>
    <tr>
        <td>Привязать к меню:</td>
        <td>
            <?
            $arrParentMenu=array();
            $arrParentMenu[0]="Корень сайта";
            foreach($menu as $v){
                $arrParentMenu[$v['id_menu']]=$v['labelMenuTire'];
            }
            $form->get('id_menu_main')->setValueOptions($arrParentMenu);
            echo $this->formSelect($form->get('id_menu_main'));
            echo $this->formElementErrors($form->get('id_menu_main'));
            ?>
    </tr>
    <tr>
        <td>Название:</td>
        <td>
            <?
            echo $this->formInput($form->get('label_menu'));
            echo $this->formElementErrors($form->get('label_menu'));
            ?>
        </td>
    </tr>
    <tr>
        <td>Alias:</td>
        <td>
            <?
            echo $this->formInput($form->get('route_menu'));
            echo $this->formElementErrors($form->get('route_menu'));
            ?>
        </td>
    </tr>
    <tr>
        <td>Сортировка:</td>
        <td>
            <?
            echo $this->formInput($form->get('order_menu'));
            echo $this->formElementErrors($form->get('order_menu'));
            ?>
        </td>
    </tr>
    <tr>
        <td>Привязка к шаблону:</td>
        <td>
            <?
            $arrType=array();
            $arrType[0]='Нет привязки';
            foreach($type as $v){
                $arrType[$v->id_type]=$v->name_type;
            }
            $form->get('id_type')->setValueOptions($arrType);
            echo $this->formSelect($form->get('id_type'));
            echo $this->formElementErrors($form->get('id_type'));
            ?>
        </td>
    </tr>
	<tr>
		<td>Текст:</td>
		<td>
			<?
			echo $this->formTextarea($form->get('text_menu'));
			echo $this->formElementErrors($form->get('text_menu'));
			?>
		</td>
	</tr>
    <tr>
	    <td>Фото:</td>
	    <td>
		    <?
		    echo $this->formFile($form->get('foto_menu'));
		    ?>
	    </td>
    </tr>
    <tr>
        <td>Показать:</td>
        <td>
            <?
            $form->get('vis_menu')->setValue(1);
            echo $this->formCheckbox($form->get('vis_menu'));
            ?>
        </td>
    </tr>
    </tbody>
</table>
<div class="button_block">
<div id="button_id_block" class="btn-group">
    <?
    echo $this->formSubmit($form->get('send'));
    ?>

</div>
</div>
<?php echo $this->form()->closeTag() ?>
