<table   id="table_id_pere">
    <thead>
    <th>№</th>
    <th>id_parent_menu</th>
    <th>Название меню</th>
    <th>Родительское меню</th>
    <th>Alias</th>
    <th>Текст</th>
    <th>Сортировка</th>
    <th>Показать</th>
    <th>События</th>
    </thead>
    </thead>
    <tbody>
    <? foreach ($menu as $v): ?>
        <tr>
            <td><?= $v->id_menu; ?></td>
            <td><?= $v->id_menu_main; ?></td>
            <td><?= $v->label_menu; ?></td>
            <td><?= $v->labelParentMenu; ?></td>
            <td><?= $v->route_menu; ?></td>
	        <td><?= mb_strlen($v->text_menu,"UTF-8"); ?></td>
            <td><?= $v->order_menu; ?></td>
            <td><?= $v->vis_menu; ?></td>
	        <td>
		        <a title="Редактировать" href='/menu/redactorMenu/<?= $v->id_menu; ?>'"><i class="icon-edit"></i>
		        <a title="Удалить"  onclick = "if(!confirm('Удалить?')) return false;"   href="/menu/deleteMenu/<?= $v->id_menu; ?>"><i class="icon-remove"></i>
	        </td>
        </tr>
    <? endforeach; ?>
    </tbody>
</table>
</form>
<script>
    $(function(){
            $.extend($.tablesorter.themes.bootstrap, {
                table: 'table table-bordered',
                header: 'bootstrap-header'// give the header a gradient background
            });
            $("#table_id_pere").tablesorter({
                theme: "bootstrap",
                widthFixed : true,
                showProcessing: true,
                headerTemplate : '{content} {icon}',
                widgets: [ 'uitheme', 'zebra', 'filter']
            });

        }
    )
</script>

