<?if($status == 2):?>
<div class="row">
			
			<div class="col-md-6">
				<div class="alert alert-success"><strong>проверочный код потвержден</strong> теперь вы можете <a href = "/login/">авторизироваться</a>.</div>
			</div>
		
		  
</div>
<?elseif($status == 1):?>
<div class="row">
			<div class="col-md-6">
				<div class="alert alert-danger"><strong>Возникла ошибка</strong>.</div>
			</div>
</div>
<?endif;?>