 <div class="login-container">
	
	<div class="login-header login-caret">
		
		<div class="login-content">
			
			 
			<!-- progress bar indicator -->
			<div class="login-progressbar-indicator">
				<h3>43%</h3>
				<span>Загрузка ...</span>
			</div>
		</div>
		
	</div>
	
	<div class="login-progressbar">
		<div></div>
	</div>
	
	<div class="login-form">
		
		<div class="login-content">
			<div class="form-login-error">
				<h3>Ошибка</h3>
				<div class = "err_content"></div>
			</div>
			
			<?php
				$form = $this->form;
				$form->setAttribute('action', $this->url('home/reg'));
				$form->prepare();
				?>
			<?=$this->form()->openTag($form)?>

				<div class="form-register-success">
					<i class="entypo-check"></i>
					<h3>Вам на почту отправлено письмо с подтверждением регистрации.</h3>
					<h3>Поздравляем вы зарегистрировались.</h3>
					<p>Перейти на <a style="color:blue !important;" href = "/">главную страницу</a> сайта</p>
				</div>
				
				<div class="form-steps">
					
					 
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="entypo-user"></i>
								</div>
								<? $element = $form->get('name');?>
								<?=$this->formElement($element)?>
								<?=$this->formElementErrors($element)?> 
							</div>
						</div>
						
					 
						
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="entypo-calendar"></i>
								</div>
								
								<? $element = $form->get('birth');?>
								<?=$this->formElement($element)?>
								<?=$this->formElementErrors($element)?>  
							</div>
						</div>
						
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="entypo-user"></i>
								</div>
								
								<? $element = $form->get('sex');?>
								<?=$this->formElement($element)?>
								<?=$this->formElementErrors($element)?>  
							</div>
						</div>
						
				 
						
					 
				 
					 		
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="entypo-mail"></i>
								</div>
								
							<? $element = $form->get('email');?>
								<?=$this->formElement($element)?>
								<?=$this->formElementErrors($element)?>  
							  
							</div>
						</div>
						
					 
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="entypo-lock"></i>
								</div>
								<? $element = $form->get('password');?>
								<?=$this->formElement($element)?>
								<?=$this->formElementErrors($element)?>
							</div>
						</div>
						
						<div class="form-group">
							<button type="submit" class="btn btn-success btn-block btn-login">
								<i class="entypo-right-open-mini"></i>
								Сохранить
							</button>
						</div>
						
					 
						
					 
					
				</div>
				
			<?=$this->form()->closeTag();?>
			
			 
		</div>
		
	</div>
	
</div>
<script src="/assets/js/neon-register.js"></script>
<script src="/assets/js/neon-login.js"></script>
<script src="/assets/js/jquery.inputmask.bundle.min.js">
</script><script src="/assets/js/fileinput.js"></script>
<script src="/assets/js/bootstrap-datepicker.js"></script>
<script src="/assets/js/bootstrap-timepicker.min.js"></script>
<script>
	 $(document).ready(function () {
		 datepicker();
	 });
</script>
