<?php
$title = 'Редактировать статью';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php

$form->setAttribute(
    'action',
    $this->url(
        'home/admin-articles/event',
        [
            'action' => 'edit',
            'id'     => $article->getId(),
        ]
    )
);
echo $this->ztbForm($this->form);
?>
<img class = "img-size" src = "/img/upload/<?=$form->get('foto')->getValue();?>">

<link rel="stylesheet" href="/assets/js/wysihtml5/bootstrap-wysihtml5.css">
<script src="/assets/js/wysihtml5/wysihtml5-0.4.0pre.min.js"></script>
<script src="/assets/js/wysihtml5/bootstrap-wysihtml5.js"></script>

<link rel="stylesheet" href="/assets/js/selectboxit/jquery.selectBoxIt.css"
      id="style-resource-3">
<script src="/assets/js/selectboxit/jquery.selectBoxIt.min.js"
        id="script-resource-11"></script>
<script src="/assets/js/bootstrap-switch.min.js"
        id="script-resource-8"></script>