<?php
$title = 'Добавить статью';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php $this->form->prepare(); ?>
<?= $this->form()->openTag($this->form) ?>
<?php foreach ($this->form as $elementOrFieldset): ?>
<div class = "row">
    <?php if ($elementOrFieldset instanceof Zend\Form\Fieldset): ?>
        <?= $this->formCollection($elementOrFieldset) ?>
    <?php else: ?>
        <?= $this->formRow($elementOrFieldset) ?>
    <?php endif; ?>
</div>
<?php endforeach; ?>
<?= $this->form()->closeTag() ?>
<link rel="stylesheet" href="/assets/js/wysihtml5/bootstrap-wysihtml5.css">
<script src="/assets/js/wysihtml5/wysihtml5-0.4.0pre.min.js"></script>
<script src="/assets/js/wysihtml5/bootstrap-wysihtml5.js"></script>

<link rel="stylesheet" href="/assets/js/selectboxit/jquery.selectboxit.css"
      id="style-resource-3">
<script src="/assets/js/selectboxit/jquery.selectboxit.min.js"
        id="script-resource-11"></script>
<script src="/assets/js/bootstrap-switch.min.js"
        id="script-resource-8"></script>
