<style>
    .ad{
        font-family: "Helvetica Neue", Helvetica, "Noto Sans", sans-serif, Arial, sans-serif;
        color: #737881;
        font-size: 12px;
        text-align: center;
        margin-top: 20px;
    }
    .a-ad{
        text-decoration: underline;
        color: #3e4048;
    }
</style>
<p class = "ad">Здесь может быть ваше место под рекламу. Пишите <a class = 'a-ad' target="_top"  href = "mailto:ad@booklot.ru">ad@booklot.ru</a></p>
