<h1>Мои книги:</h1>

<?php if ($paginator->count() != 0): ?>
    <div class="posts-list-4-cols">
        <? foreach ($paginator as $book): ?>
            <?
            $params = [];
            $params['book'] = $book->getBook()->getAlias();
            $params['s'] = $book->getBook()->getNS();
            $params['alias_menu'] = $book->getBook()->getNAliasMenu();
            $route_ = 'home/genre/one/book';
            ?>
            <a href="<?= $this->url($route_, $params) ?>"><?= $book->getBook()
                    ->getName(); ?></a>

        <? endforeach; ?>
    </div>

    <div class="text-center">
        <?

        echo $this->paginationControl(
            $paginator,
            'Sliding',
            'pagination',
            array(
                'route'  => 'home/cabinet/my-book',
                'action' => 'list',
            )
        ); ?>
    </div>
<? else: ?>
    Ваша библиотека пуста.
<? endif; ?>

