<?php
echo $this->partial('application/menu/admin-book',
    [
        'book_id' => $book_id,
        'route' => 'home/admin-text'
    ]
);
?>
<?php
$title = 'Добавить текст';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php

$form->setAttribute('action', $this->url('home/admin-text',
    [
            'action' => 'add',
            'id' => $book->getId()
    ]
)
);
echo $this->ztbForm($this->form);
?>
<link rel="stylesheet" href="/assets/js/wysihtml5/bootstrap-wysihtml5.css">
<script src="/assets/js/wysihtml5/wysihtml5-0.4.0pre.min.js"></script>
<script src="/assets/js/wysihtml5/bootstrap-wysihtml5.js"></script>



