<?php
$title = 'Добавить текст';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php

$form->setAttribute('action', $this->url('home/admin-text',
    [
            'action' => 'edittext',
            'id' => $text->getId()
    ]
)
);
echo $this->ztbForm($this->form);
?>
<link rel="stylesheet" href="/assets/js/wysihtml5/bootstrap-wysihtml5.css">
<script src="/assets/js/wysihtml5/wysihtml5-0.4.0pre.min.js"></script>
<script src="/assets/js/wysihtml5/bootstrap-wysihtml5.js"></script>



