<!--<div class="row-fluid">-->
<!--	<div class="span2">-->
<!--		<a title="Меню" href="/menu">-->
<!--			<img class="img-polaroid" src="/img/menu_admin.jpg" />-->
<!--			<div class="admin_gl">Менеджер меню</div>-->
<!--		</a>-->
<!--	</div>-->
<!--	<div class="span2">-->
<!--		<a title="Меню" href="/template">-->
<!--			<img class="img-polaroid" src="/img/menu_admin.jpg" />-->
<!--			<div class="admin_gl">Менеджер шаблонов</div>-->
<!--		</a>-->
<!--	</div>-->
<!--	<div class="span2">-->
<!--		<a title="Меню" href="/content">-->
<!--			<img class="img-polaroid" src="/img/menu_admin.jpg" />-->
<!--			<div class="admin_gl">Менеджер контента</div>-->
<!--		</a>-->
<!--	</div>-->
<!--	<div class="span2">-->
<!--		<a title="Меню" href="/pay">-->
<!--			<img class="img-polaroid" src="/img/menu_admin.jpg" />-->
<!--			<div class="admin_gl">Заказы</div>-->
<!--		</a>-->
<!--	</div>-->
<!--</div>-->