<div class="login-container">
	
	<div class="login-header login-caret">
		
		<div class="login-content">
			
			<a href="index.html" class="logo">
			 
			</a>
			
			<p class="description"></p>
			
			<!-- progress bar indicator -->
			<div class="login-progressbar-indicator">
				<h3>43%</h3>
				<span>Загрузка ...</span>
			</div>
		</div>
		
	</div>
	
	<div class="login-progressbar">
		<div></div>
	</div>
	
	<div class="login-form">
		
		<div class="login-content">
			
			<div class="form-login-error">
				<h3>Неправильное имя или пароль</h3>
				<p>Попробуйте ввести снова.</p>
			</div>
			<?php
				$form = $this->form;
				$form->setAttribute('action', $this->url('home/slash/auth',array('subdomain'=>'www.booklot.ru')));
				$form->prepare();
				?>
			<?=$this->form()->openTag($form)?>
				<div class="form-group">
					
					<div class="input-group">
						<div class="input-group-addon">
							<i class="entypo-mail"></i>
						</div>
						<? $element = $form->get('username');?>
						<?=$this->formElement($element)?>
						<?=$this->formElementErrors($element)?>
						 
					</div>
					
				</div>
				
				<div class="form-group">
					
					<div class="input-group">
						<div class="input-group-addon">
							<i class="entypo-key"></i>
						</div>
						<? $element = $form->get('password');?>
						<?=$this->formElement($element)?>
						<?=$this->formElementErrors($element)?>
						
					 </div>
				
				</div>
				
				<div class="form-group">
					<button type="submit" class="btn btn-primary btn-block btn-login">
						<i class="entypo-login"></i>
						Вход
					</button>
				</div>
				
 
		</div>
		<?=$this->form()->closeTag();?>
	</div>
	
</div>
<script src="/assets/js/neon-login.js"></script>

