<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name='yandex-verification' content='569a2f4067bc1bbe' />
	<meta name="google-site-verification" content="vST5iHSixoR0eTIWInejKvCrb66GMeQwt3LlHmypRjA" />
	<?php echo $this->headTitle("Книги «BOOKLOT.RU»") ->setSeparator(' - ')->setAutoEscape(false);?>
	<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
	<link rel="icon" href="/favicon.ico" type="image/x-icon" />
	<link rel="stylesheet" href="/assets/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css">
	<link rel="stylesheet" href="/assets/css/font-icons/entypo/css/entypo.css">
	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic">
	<link rel="stylesheet" href="/assets/css/bootstrap.css">
	<link rel="stylesheet" href="/assets/css/neon-core.css">
	<link rel="stylesheet" href="/assets/css/neon-theme.css">
	<link rel="stylesheet" href="/assets/css/neon-forms.css">
	<link rel="stylesheet" href="/assets/css/custom.css">
	<link rel="stylesheet/less" type="text/css" href="/css/style.less">
	<script src="/assets/js/jquery-1.11.0.min.js"></script>
    <script src="/node_modules/jquery.iframetracker/dist/jquery.iframetracker.js"></script>
	<!--[if lt IE 9]><script src="/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->
	
	
	<?php echo $this->headScript()
		->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
		->prependFile($this->basePath() . '/js/bootstrap.min.js')->prependFile($this->basePath() . '/js/less.js')
		->prependFile($this->basePath() . '/js/my.js')
	?>
	
	<script src="/assets/js/gsap/main-gsap.js"></script>
	<script src="/assets/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js"></script>
	<script src="/assets/js/bootstrap.js"></script>
	<script src="/assets/js/joinable.js"></script>
	<script src="/assets/js/resizeable.js"></script>
	<script src="/assets/js/neon-api.js"></script>
	<script src="/assets/js/jquery.validate.min.js"></script>
	
	
	
		<!-- JavaScripts initializations and stuff -->
	<script src="/assets/js/neon-custom.js"></script>


	<!-- Demo Settings -->
	<script src="/assets/js/neon-demo.js"></script> 
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-2745956118385780",
    enable_page_level_ads: true
  });
</script>

</head>
<body class="page-body login-page login-form-fall">

<?if(isset($_GET['bug'])):?>
<?
var_dump($this->getHelperPluginManager()->getServiceLocator()->get('AuthService')->getStorage()->read());
var_dump(get_class_methods($this));?>
	<?endif;?>
<!-- This is needed when you send requests via Ajax -->
<script type="text/javascript">
var baseurl = '';
</script>


<?echo $this -> content;?>
 
</body>
</html>
