<?global $site;?>
<?php $container = $this->navigation()->breadcrumbs()  ?>
<?php /* @var $container \Zend\View\Helper\Navigation\Breadcrumbs */ ?>
<?php $navigation = $container->getContainer() ?>
<?php /* @var $navigation \Zend\Navigation\Navigation */ ?>

<ol class="breadcrumb bc-3">
	<?php foreach($this->pages as $page): ?>
		<?
		$params = $page->getParams();
		//var_dump(($page->getHref()));

		?>
		<?php /* @var $page \Zend\Navigation\Page\Mvc */ ?>
		<?php if( ! $page->isActive()): ?>
			<li>
				<a href="<?php echo str_replace('http://', 'https://', $page->getHref()); ?>"><i class="<?php echo $page->getClass();?>"></i>
					<?php echo $page->getLabel() ?></a>
			</li>
		<?php else: ?>
			<li class="active"><i class="<?php echo $page->getClass();?>"></i>
				<?php if($container->getLinkLast()): ?>

				<a href="<?php echo str_replace('http://', 'https://', $page->getHref()); ?>"><?php endif ?>
					<?php echo $page->getLabel() ?>
					<?php if($container->getLinkLast()): ?></a><?php endif ?>
			</li>
		<?php endif ?>
	<?php endforeach ?>
</ol>
