<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name='yandex-verification' content='569a2f4067bc1bbe'/>
	<meta name="google-site-verification" content="dpl_zcPq41t1zUBvzm9BJJhoz60UvGpBh52TKVqoFus"/>
    <meta name="verify-admitad" content="4935680aa6"/>
    <link rel="alternate" type="application/rss+xml" title="RSS Feed for booklot.org"   href="https://www.booklot.org/feed.xml" />
    <?php echo $this->headTitle("Книги «BOOKLOT.ORG»")->setSeparator(' - ')->setAutoEscape(false); ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <link rel="icon" href="/favicon.ico" type="image/x-icon"/>
    <?php echo $this->headLink() ?>
    <link rel="stylesheet" type="text/css" href="/assets/css/font-icons/entypo/css/entypo.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/neon-core.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/neon-theme.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/neon-forms.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/custom.css">
    <link rel="stylesheet/less" type="text/css" href="/css/style.less">
    <link rel="alternate" type="application/rss+xml" title="Последние добавленные книги" href="https://www.booklot.org/feed.xml" />
    <script src="/assets/js/jquery-1.11.0.min.js"></script>
    <script src="/node_modules/jquery.iframetracker/dist/jquery.iframetracker.js"></script>
    <script src="/js/less.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/html5.js"></script>
    <script src="/js/my.js"></script>
<!--    --><?//=$this->ad()->config();?>
</head>
<body class="page-body">
<div class="page-container">
    <div class="sidebar-menu">
        <div class="sidebar-menu-inner">
            <header class="logo-env">
                <div class="logo">
                    <a href="/" class="logobook"> BOOKLOT.ORG </a>
                </div>
                <div class="sidebar-collapse">
                    <a href="#" class="sidebar-collapse-icon"> <i class="entypo-menu"></i> </a>
                </div>
                <div class="sidebar-mobile-menu visible-xs">
                    <a href="#" class="with-animation"> <i class="entypo-menu"></i> </a>
                </div>
            </header>
            <ul id="main-menu" class="main-menu">
                <li class="active opened visible">
                    <?
                    echo $this->navigation('NavigationDynamic')->menu()->setPartial('layout/left_menu', 'default');
                    ?>
                </li>
            </ul>
        </div>
    </div>
    <div class="main-content">
        <?=$this->button_search();?>
        <?=$this->ad()->name('top');?>
        <? if ($this->arrUser): ?>
            <?=$this->button()->userParams();?>
        <? else: ?>
            <div class="col-md-12 clearfix">
                <ul class="col-sm-12  list-inline">
                    <li>
                        <a href="/reg/"> Регистрация <i class="entypo-user-add right"></i> </a>
                    </li>
                    <li>
                        <a href="/login/"> Авторизация <i class="entypo-login right"></i> </a>
                    </li>
                </ul>
            </div>
        <? endif; ?>
        <div class="row container-fluid">
            <?= $this->content; ?>
            <?=$this->ad()->name('footer');?>
            <footer class="main">
                &copy; 2012-<?=date('Y')?> <strong>Электронная библиотека</strong> <a href="/" target="_blank">booklot.org</a>
            </footer>
        </div>
        <script src="/assets/js/gsap/main-gsap.js"></script>
        <script src="/assets/js/bootstrap.js"></script>
        <script src="/assets/js/resizeable.js"></script>
        <script src="/assets/js/neon-api.js"></script>
        <script src="/assets/js/neon-custom.js"></script>
        <script src="/assets/js/toastr.js" id="script-resource-8"></script>

	    <!-- Global site tag (gtag.js) - Google Analytics -->
	    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-68155989-2"></script>
	    <script>
		    window.dataLayer = window.dataLayer || [];
		    function gtag(){dataLayer.push(arguments);}
		    gtag('js', new Date());

		    gtag('config', 'UA-68155989-2');
	    </script>
	    <!-- Yandex.Metrika counter -->
	    <script type="text/javascript" >
		    (function (d, w, c) {
			    (w[c] = w[c] || []).push(function() {
				    try {
					    w.yaCounter51052757 = new Ya.Metrika2({
						    id:51052757,
						    clickmap:true,
						    trackLinks:true,
						    accurateTrackBounce:true
					    });
				    } catch(e) { }
			    });

			    var n = d.getElementsByTagName("script")[0],
				    s = d.createElement("script"),
				    f = function () { n.parentNode.insertBefore(s, n); };
			    s.type = "text/javascript";
			    s.async = true;
			    s.src = "https://mc.yandex.ru/metrika/tag.js";

			    if (w.opera == "[object Opera]") {
				    d.addEventListener("DOMContentLoaded", f, false);
			    } else { f(); }
		    })(document, window, "yandex_metrika_callbacks2");
	    </script>
	    <noscript><div><img src="https://mc.yandex.ru/watch/51052757" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
	    <!-- /Yandex.Metrika counter -->
        <div class="modal fade" id="modal-8">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"
                                aria-hidden="true">&times;
                        </button>
                        <h4 class="modal-title">Реклама</h4></div>
                    <div class="modal-body">
                        Вы действительно хотите отключить рекламу на 1 час.
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-info close-reklama">Сохранить</button>
                        <button type="button" class="btn btn-default"
                                data-dismiss="modal">Закрыть
                        </button>
                    </div>
                </div>
            </div>
        </div>
</body>
</html>
