<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name='yandex-verification' content='569a2f4067bc1bbe'/>
    <meta name="google-site-verification" content="vST5iHSixoR0eTIWInejKvCrb66GMeQwt3LlHmypRjA"/>
    <meta name="verify-admitad" content="4935680aa6"/>
    <link rel="alternate" type="application/rss+xml" title="RSS Feed for booklot.ru"   href="https://www.booklot.ru/feed.xml" />
    <?php echo $this->headTitle("Книги «BOOKLOT.RU»")->setSeparator(' - ')->setAutoEscape(false); ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <link rel="icon" href="/favicon.ico" type="image/x-icon"/>
    <?php echo $this->headLink() ?>
    <link rel="stylesheet" type="text/css" href="/assets/css/font-icons/entypo/css/entypo.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/neon-core.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/neon-theme.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/neon-forms.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/custom.css">
    <link rel="stylesheet/less" type="text/css" href="/css/style.less">

    <script src="/assets/js/jquery-1.11.0.min.js"></script>
    <script src="/js/less.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/html5.js"></script>
    <script src="/js/my.js"></script>

    <!--[if lt IE 9]>
    <script src="/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-2745956118385780",
            enable_page_level_ads: true
        });
    </script>
</head>
<body class="page-body">

<div class="page-container">

    <div class="sidebar-menu">

        <div class="sidebar-menu-inner">

            <header class="logo-env">

                <div class="logo">
                    <a href="/" class="logobook"> BOOKLOT.RU </a>
                </div>

                <div class="sidebar-collapse">
                    <a href="#" class="sidebar-collapse-icon"> <i class="entypo-menu"></i> </a>
                </div>

                <div class="sidebar-mobile-menu visible-xs">
                    <a href="#" class="with-animation"> <i class="entypo-menu"></i> </a>
                </div>

            </header>


            <ul id="main-menu" class="main-menu">

                <li class="active opened visible">
                    <?
                    echo $this->navigation('NavigationDynamic')->menu()->setPartial('layout/left_menu', 'default');
                    ?>
                </li>
            </ul>

        </div>

    </div>

    <div class="main-content">

        <?=$this->button_search();?>

        <? if ($this->arrUser): ?>
            <?=$this->button()->userParams();?>
        <? else: ?>
            <div class="col-md-12 clearfix">
                <ul class="col-sm-12  list-inline">
                    <!-- Language Selector -->
                    <li>
                        <a href="/reg/"> Регистрация <i class="entypo-user-add right"></i> </a>
                    </li>
                    <li>
                        <a href="/login/"> Авторизация <i class="entypo-login right"></i> </a>
                    </li>
                </ul>
            </div>
            <div class="row">

                <!-- Raw Links -->
                <div class="col-md-12 clearfix">
                    <div class="row">
                        <div class="col-sm-12">
                            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                            <!-- b_resize_(all)bookAction -->
                            <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-2745956118385780" data-ad-slot="6354762283" data-ad-format="auto"></ins>
                            <script>
                                (adsbygoogle = window.adsbygoogle || []).push({});
                            </script>
                        </div>

                    </div>
                </div>

            </div>

        <? endif; ?>


        <div class="row container-fluid">


            <?= $this->content; ?>


            <!-- Footer -->
            <footer class="main">

                &copy; 2012-2016 <strong>Электронная библиотека</strong> <a href="/" target="_blank">booklot.ru</a>

            </footer>
        </div>


        <!-- Bottom scripts (common) -->
        <script src="/assets/js/gsap/main-gsap.js"></script>
<!--        <script src="/assets/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js"></script>-->
        <script src="/assets/js/bootstrap.js"></script>
<!--        <script src="/assets/js/joinable.js"></script>-->
        <script src="/assets/js/resizeable.js"></script>
        <script src="/assets/js/neon-api.js"></script>


        <!-- JavaScripts initializations and stuff -->
        <script src="/assets/js/neon-custom.js"></script>
        <!-- notification -->
        <script src="/assets/js/toastr.js" id="script-resource-8"></script>

        <!--         Yandex.Metrika counter-->
        <script type="text/javascript">
            (function (d, w, c) {
                (w[c] = w[c] || []).push(function () {
                    try {
                        w.yaCounter12310006 = new Ya.Metrika({
                            id: 12310006,
                            clickmap: true,
                            trackLinks: true,
                            accurateTrackBounce: true,
                            webvisor: true
                        });
                    } catch (e) {
                    }
                });

                var n = d.getElementsByTagName("script")[0],
                    s = d.createElement("script"),
                    f = function () {
                        n.parentNode.insertBefore(s, n);
                    };
                s.type = "text/javascript";
                s.async = true;
                s.src = "https://mc.yandex.ru/metrika/watch.js";

                if (w.opera == "[object Opera]") {
                    d.addEventListener("DOMContentLoaded", f, false);
                } else {
                    f();
                }
            })(document, window, "yandex_metrika_callbacks");
        </script>
        <noscript>
            <div><img src="https://mc.yandex.ru/watch/12310006" style="position:absolute; left:-9999px;" alt=""/></div>
        </noscript>
        <!--         /Yandex.Metrika counter-->

</body>
</html>
