<div class="row">

    <div class="col-md-12">

        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-title">Список</div>

                <div class="panel-options">
                    <a href="#sample-modal" data-toggle="modal" data-target="#sample-modal-dialog-1" class="bg"><i class="entypo-cog"></i></a>
                    <a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a>
                    <a href="#" data-rel="reload"><i class="entypo-arrows-ccw"></i></a>
                    <a href="#" data-rel="close"><i class="entypo-cancel"></i></a>
                </div>
            </div>

            <div class="panel-body">

                <div class="row">
                    <div class="col-md-12">

                        <ul>
                            <li><a href = "viewfb2">Загрузка FB2</a></li>
                        </ul>

                    </div>
                </div>

            </div>

        </div>

    </div>
</div>


