<div class="row">

    <div class="col-md-12">

        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-title">Список</div>

                <div class="panel-options">
                    <a href="#sample-modal" data-toggle="modal" data-target="#sample-modal-dialog-1" class="bg"><i class="entypo-cog"></i></a>
                    <a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a>
                    <a href="#" data-rel="reload"><i class="entypo-arrows-ccw"></i></a>
                    <a href="#" data-rel="close"><i class="entypo-cancel"></i></a>
                </div>
            </div>

            <div class="panel-body">

                <div class="row">
                    <div class="col-md-12">



                                <form method="POST" enctype="multipart/form-data">
                                    <input class = "form-control" type="file" name = "file" value="Файл" /><br>
                                    <input class = "btn btn-default" type="submit"  value="Загрузить">
                                </form>



                    </div>
                </div>

            </div>

        </div>

    </div>
</div>


