<h1>Топ 10 книг, разных жанров</h1>

<ol class="breadcrumb bc-3">

    <li>
        <a href="/"><i class="entypo-home"></i>
            Главная</a>
    </li>
    <li class="active"><i class="entypo-trophy"></i>
        Топ 10								</li>
</ol>

<form method="GET">
    <div class="input-group">
        <input <? if (isset($get['name_zhanr'])): ?> value="<?= $get['name_zhanr']; ?>" <? endif; ?>
                type="text" class="form-control" placeholder="Введите жанр" name="name_zhanr"> <span
                class="input-group-btn"> <button class="btn btn-primary"
                                                 type="submit">Поиск</button> </span>
    </div>
</form>
<br><br>
<div class="list-group">
    <? foreach ($mzhanr as $zhanr): ?>
        <a href="<?=$this->url('home/tops/one', ['alias' => $zhanr->getAlias()])?>" class="list-group-item">
            Топ 10 книг "<?= $zhanr->getName(); ?>"
        </a>
    <? endforeach; ?>

</div>