<h1>Топ 10 книг "<?=$mzhanr->getName();?>"</h1>

<ol class="breadcrumb bc-3">
    <li>
        <a href="/"><i class="entypo-home"></i>
            Главная
        </a>
    </li>
    <li>
        <a href = "/tops/"><i class="entypo-trophy"></i>
        Топ 10
        </a>
    </li>
</ol>

<?if($mzhanr->getSeoText() != ''):?>
<blockquote class="blockquote-default"><p><strong>О жанре "<?=$mzhanr->getName();?>" описание</strong>
    </p>
    <p>
        <small>
            <?=$mzhanr->getSeoText();?>
        </small>
    </p>
</blockquote>
<?endif;?>
<?foreach($books as $k => $book):?>
    <?
    $params = [];
    $params['book'] = $book->getAlias();
    $params['s'] = $book->getZhanr()[0]->getParent()->getAlias();
    $params['alias_menu'] = $book->getZhanr()[0]->getAlias();
    $route_ = 'home/genre/one/book';
    ?>
    <div class="member-entry">
        <span class="badge badge-info my-span" ><?=++$k;?></span>
        <a href="<?=$this->url($route_, $params)?>" class="member-img">
            <?if(stristr($book->getFoto(), "\n") or empty($book->getFoto()) or !file_exists($_SERVER['DOCUMENT_ROOT'].'/templates/newimg/small/'.$book->getFoto())):?>
                <img  class="img-rounded" src="/templates/newimg/small/nofoto.jpg"><i class="entypo-forward"></i>
            <?else:?>
                <img  class="img-rounded" src="/templates/newimg/small/<?=$book->getFoto();?>"><i class="entypo-forward"></i>
            <?endif;?>
        </a>
        <div class="member-details">
            <h4>
                <a href="<?=$this->url($route_, $params)?>">
                    <?=$book->getName();?>
                </a>
            </h4>
            <div class="row info-list my-top">
                <?=strip_tags($book->getTextSmall());?>
            </div>
        </div>
    </div>
<?endforeach;?>

<script type="text/javascript">
    VK.init({apiId: 2786799, onlyWidgets: true});
</script>

<h5 class="text-left">Комментарии с других ресурсов:</h5>
<div id="vk_comments" class = "margin-button"></div>
<script type="text/javascript">
    VK.Widgets.Comments("vk_comments", {limit: 10, width: "auto", attach: "*"});
</script>
