<h1>Топ 10 книг "<?=$mzhanr->getName();?>"</h1>
<?if($mzhanr->getSeoText() != ''):?>
<blockquote class="blockquote-default"><p><strong>О жанре "<?=$mzhanr->getName();?>" описание</strong>
    </p>
    <p>
        <small>
            <?=$mzhanr->getSeoText();?>
        </small>
    </p>
</blockquote>
<?endif;?>
<?foreach($books as $book):?>
    <?
    $params = [];
    $params['book'] = $book->getAlias();
    $params['s'] = $book->getZhanr()[0]->getParent()->getAlias();
    $params['alias_menu'] = $book->getZhanr()[0]->getAlias();
    $route_ = 'home/genre/one/book';
    ?>
    <div class="member-entry">
        <a href="<?=$this->url($route_, $params)?>" class="member-img">
            <?if(stristr($book->getFoto(), "\n") or empty($book->getFoto()) or !file_exists($_SERVER['DOCUMENT_ROOT'].'/templates/newimg/small/'.$book->getFoto())):?>
                <img  class="img-rounded" src="/templates/newimg/small/nofoto.jpg"><i class="entypo-forward"></i>
            <?else:?>
                <img  class="img-rounded" src="/templates/newimg/small/<?=$book->getFoto();?>"><i class="entypo-forward"></i>
            <?endif;?>
        </a>
        <div class="member-details">
            <h4>
                <a href="<?=$this->url($route_, $params)?>">
                    <?=$book->getName();?>
                </a>
            </h4>
            <div class="row info-list my-top">
                <?=strip_tags($book->getTextSmall());?>
            </div>
        </div>
    </div>

<?endforeach;?>
