<?php if ($this->pageCount > 1): ?>

    <?php
    $this->headLink(
        array(
            'rel'  => 'canonical',
            'href' => $this->url(
                $this->route,
                array(
                    'action' => $this->action,
                ),
                array(
                    'query' => $_GET,
                )
            ),
        )
    );


    ?>
    <ul class="pagination">
        <li <?php echo !isset($this->previous) ? 'class="disabled"' : ''; ?>>
            <a href="<?= $this->url(
                $this->route,
                array(
                    'action' => $this->action,
                ),
                array(
                    'query' => $_GET,
                )
            ); ?>">&laquo;</a>
        </li>
        <? if ($this->previous != null): ?>
            <li

                <?php echo !isset($this->previous) ? 'class="disabled"'
                    : ''; ?>>
                <a href="<?= $this->url(
                    $this->route,
                    array(
                        'action' => $this->action,
                        'paged'  => $this->previous,
                    ),
                    array(
                        'query' => $_GET,
                    )
                ); ?>">&lsaquo;</a>
            </li>
        <? endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>

            <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>>
                <a href="<?= $this->url(
                    $this->route,
                    array(
                        'action' => $this->action,
                        'paged'  => $page,
                    ),
                    array(
                        'query' => $_GET,
                    )
                ); ?>"><?= $page; ?></a>
            </li>
        <?php endforeach; ?>

        <!-- Next page link -->
        <li <?php echo !isset($this->next) ? 'class="disabled"' : ''; ?>>
            <a href="<?= $this->url(
                $this->route,
                array(
                    'action' => $this->action,
                    'paged'  => $this->next,
                ),
                array(
                    'query' => $_GET,
                )
            ); ?>">&rsaquo;</a>
        </li>
        <!-- Last page link -->
        <li <?php echo !isset($this->next) ? 'class="disabled"' : ''; ?>>
            <a href="<?= $this->url(
                $this->route,
                array(
                    'action' => $this->action,
                    'paged'  => $this->last,
                ),
                array(
                    'query' => $_GET,
                )
            ); ?>">&raquo;</a>
        </li>
    </ul>

<?php endif; ?>

