<?php if( $this->pageCount > 1 ):?>
		<ul class = "pagination">
			<li <?php echo ! isset( $this-> previous ) ? 'class="disabled"' : ''; ?>>
				<a rel = "canonical"  href="<?= $this->url(
					$this->route,
					array(
						'action'=>$this -> action,
						'alias_menu' => $this->alias_menu
					),
					array('query' =>
					      $_GET
					)
				); ?>">&laquo;</a>
			</li>
			<li
				<?php echo ! isset( $this->previous ) ? 'class="disabled"' : ''; ?>>
				<a  href="<?= $this->url(
					$this->route,
					array(
						'action'=>$this -> action,
						'page_author' => $this -> previous,
						'alias_menu' => $this->alias_menu
					),
					array('query' =>
					      $_GET
					)
				); ?>">&lsaquo;</a>
			</li>
			<!-- Numbered page links -->
			<?php foreach( $this->pagesInRange as $page ): ?>

				<li <?php echo $page == $this->current ? 'class="active"' : ''; ?>>
					<a  href="<?= $this->url(
						$this->route,
						array(
							'action'=>$this -> action,
							'page_author' => $page,
							'alias_menu' => $this->alias_menu
						),
						array('query' =>
						      $_GET
						)
					); ?>"><?=$page;?></a>
				</li>
			<?php endforeach; ?>
			<!-- Next page link -->
			<li <?php echo ! isset( $this->next ) ? 'class="disabled"' : ''; ?>>
				<a  href="<?= $this->url(
					$this->route,
					array(
						'action'=>$this -> action,
						'page_author' => $this -> next,
						'alias_menu' => $this->alias_menu
					),
					array('query' =>
					      $_GET
					)
				); ?>">&rsaquo;</a>
			</li>
			<!-- Last page link -->
			<li <?php echo ! isset( $this->next ) ? 'class="disabled"' : ''; ?>>
				<a  href="<?= $this->url(
					$this->route,
					array(
						'action'=>$this -> action,
						'page_author' => $this->last,
						'alias_menu' => $this->alias_menu
					),
					array('query' =>
					      $_GET
					)
				); ?>">&raquo;</a>
			</li>
		</ul>
<?php endif; ?>

