<div class="row">
    <div class="col-md-12 col-sm-8 clearfix">
        <ul class="user-info pull-left pull-none-xsm">
            <li class="profile-info dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <? if ($user->getFoto() == 'user.jpg'): ?>
                        <img width="44" class="img-circle" alt="" src="<?=IMAGE_URL?>/resize/200/<?= ($user->getSex(
                            ) == 'M') ? 'userman.jpg' : 'userwomen.jpg'; ?>">
                    <? else: ?>
                        <img width="44" class="img-circle" alt="" src="<?=IMAGE_URL?>/resize/200/<?= $user->getFoto(); ?>">
                    <? endif; ?>
                    <span style=""><?= $user->getName(); ?></span>
                </a>
                <br>
                <a class="logout-text" href="<?= $this->url('home/logout'); ?>"> Выход <i
                            class="entypo-logout left"></i> </a>
                <ul class="dropdown-menu">
                    <li class="caret"></li>
                    <li>
                        <a href="<?= $this->url('home/cabinet', ['action' => 'edit']); ?>"> <i class="entypo-user"></i>
                            Измениь профиль</a>
                    </li>
                </ul>
            </li>
        </ul>
        <ul class="user-info pull-left  pull-none-xsm">

            <li class="notifications dropdown">
                <a data-close-others="true"
                   href="<?= $this->url('home/cabinet/comments', ['action' => 'comments']); ?>">
                    <i class="entypo-comment"></i>
                    <span class="badge badge-info">
                        <?= $user->getComments(); ?>
                    </span>
                </a>
            </li>

            <li class="notifications dropdown">
                <a data-close-others="true" href="<?= $this->url('home/cabinet/my-book', ['action' => 'my-book']); ?>">
                    <i class="entypo-book"></i>
                    <span class="badge badge-info">
                        <?= $user->getMyBook(); ?>
                    </span>
                </a>
            </li>

            <li class="notifications dropdown">
                <a data-close-others="true" href="<?= $this->url('home/cabinet/my-like', ['action' => 'my-like']); ?>">
                    <i class="entypo-heart"></i>
                    <span class="badge badge-info">
                        <?= $user->getLikeBook(); ?>
                    </span>
                </a>
            </li>

            <li class="notifications dropdown">
                <a data-close-others="true"
                   href="<?= $this->url('home/cabinet/my-book-status', ['action' => 'my-book-status']); ?>">
                    <i class="entypo-archive"></i>
                    <span class="badge badge-info">
                        <?= $user->getCountStatusBook(); ?>
                    </span>
                </a>
            </li>
            <? if ($user->getRole() == 'admin'): ?>
                <li class="notifications dropdown">
                    <a data-close-others="true" href="<?= $this->url('home/admin-articles'); ?>">
                        <i class="entypo-doc-text"></i>
                    </a>
                </li>
            <? endif; ?>
            <? if ($user->getRole() == 'admin'): ?>
                <li class="notifications dropdown">
                    <a data-close-others="true" href="<?= $this->url('home/admin-book', ['action' => 'index']); ?>">
                        <i class="entypo-flow-cascade"></i>
                    </a>
                </li>
            <? endif; ?>
            <? if ($user->getRole() == 'admin'): ?>
                <li class="notifications dropdown">
                    <a data-close-others="true" href="<?= $this->url( 'home/admin-fb',
                        ['action' => 'add']); ?>">
                        <i class="entypo-list-add"></i>
                    </a>
                </li>
            <? endif; ?>
            <? if ($user->getRole() == 'admin'): ?>
                <li class="notifications dropdown">
                    <a data-close-others="true" href="<?= $this->url('home/admin-ad', ['action' => 'index']); ?>">
                        <i class="entypo-rocket"></i>
                    </a>
                </li>
            <? endif; ?>
        </ul>
    </div>
</div>