<h1>Комментарии(й):</h1>

<?php if ($paginator->count() != 0): ?>
    <div class="posts-list-4-cols">
        <? foreach ($paginator as $comment): ?>
            <?
            $params = [];
            $params['book'] = $comment->getIdContent()->getAlias();
            $params['s'] = $comment->getIdContent()->getZhanr()[0]->getParent()
                ->getAlias();
            $params['alias_menu'] = $comment->getIdContent()->getZhanr(
            )[0]->getAlias();
            $route_ = 'home/genre/one/book';
            ?>
            <a href="<?= $this->url(
                $route_,
                $params
            ) ?>"><?= $comment->getIdContent()->getName(); ?></a>


        <? endforeach; ?>
    </div>

    <div class="text-center">
        <?

        echo $this->paginationControl(
            $paginator,
            'Sliding',
            'pagination',
            array(
                'route'  => 'home/cabinet/comments',
                'action' => 'comments',
            )
        ); ?>
    </div>
<?else:?>
    Нет ни одного комментария.
<? endif; ?>


