<div class="my-lib-block">
    <div class="row">
        <div class="col-sm-4" >
            <?php echo $this->my_book($book['id'])?>
        </div>
        <div class="col-sm-6">
            <?php echo $this->my_book_status($book['id'])?>
        </div>
        <div class="col-sm-2">
            <?php echo $this->my_book_like($book['id'])?>
        </div>
    </div>
</div>



<link rel="stylesheet" href="/assets/js/selectboxit/jquery.selectBoxIt.css"
      id="style-resource-3">
<script src="/assets/js/selectboxit/jquery.selectBoxIt.min.js"
        id="script-resource-11"></script>
<script src="/assets/js/bootstrap-switch.min.js"
        id="script-resource-8"></script>