<div id = "help">
	<table class="table table-striped table-bordered table-hover ">
		<thead>
		<tr><th>Название</th>
			<th>Значение</th>
			<th>Действие</th>
		</tr></thead>
		<tbody>
		<tr>
			<td>Категория</td>
			<td>
				<select  name="category[]">
					<option value="0">Не выбрано</option>
					<?foreach($category as $v):?>
						<option value="<?=$v -> id_category?>"><?=$v -> name_category?></option>
					<?endforeach?>
				</select>
			</td>
			<td>
				<button class = "btn" onclick="category.del(this)">Удалить</button>
			</td>
		</tr>
		</tbody>
	</table>
</div>
<?echo $this->form()->openTag($form);?>
<table class="table table-striped table-bordered table-hover typetable">
    <thead>
    <th>Название</th>
    <th>Значение</th>
    </thead>
    <tbody>
    <tr>
        <td>Название:</td>
        <td>
            <?
            echo $this->formInput($form->get('name_brand'));
            echo $this->formElementErrors($form->get('name_brand'));
            ?>
        </td>
    </tr>
    <tr>
        <td>Alias:</td>
        <td>
            <?
            echo $this->formInput($form->get('alias_brand'));
            echo $this->formElementErrors($form->get('alias_brand'));
            ?>
        </td>
    </tr>
	<tr>
		<td>Текст:</td>
		<td>
			<?
			echo $this->formInput($form->get('text_brand'));
			echo $this->formElementErrors($form->get('text_brand'));
			?>
		</td>
	</tr>
    <tr>
        <td>Сортировка:</td>
        <td>
            <?
            echo $this->formInput($form->get('order_brand'));
            echo $this->formElementErrors($form->get('order_brand'));
            ?>
        </td>
    </tr>
    </tbody>
</table>

<div class = "category_block">

</div>

<div class="button_block">
<div id="button_id_block" class="btn-group">
    <?
    echo $this->formSubmit($form->get('send'));
    ?>
	<input type="button" value="Добавить категорию" class="btn" name="cat" onclick="category.add();">
</div>
</div>
<?php echo $this->form()->closeTag() ?>
