<?echo $this->form()->openTag($form);?>
<table class="table table-striped table-bordered table-hover typetable">
    <thead>
    <th>Название</th>
    <th>Значение</th>
    </thead>
    <tbody>
    <tr>
        <td>Название:</td>
        <td>
            <?
            echo $this->formInput($form->get('name_model'));
            echo $this->formElementErrors($form->get('name_model'));
            ?>
        </td>
    </tr>
    <tr>
        <td>Alias:</td>
        <td>
            <?
            echo $this->formInput($form->get('alias_model'));
            echo $this->formElementErrors($form->get('alias_model'));
            ?>
        </td>
    </tr>
    <tr>
        <td>Брэнд:</td>
        <td>
            <?
            $arrBrand=array();
            foreach($brand as $v){
                $arrBrand[$v->id_brand]=$v->name_brand;
            }
            $form->get('id_brand')->setValueOptions($arrBrand);
            echo $this->formSelect($form->get('id_brand'));
            echo $this->formElementErrors($form->get('id_brand'));
            ?>
    </tr>
    <tr>
        <td>Сортировка:</td>
        <td>
            <?
            echo $this->formInput($form->get('order_model'));
            echo $this->formElementErrors($form->get('order_model'));
            ?>
        </td>
    </tr>
    </tbody>
</table>
<div class="button_block">
<div id="button_id_block" class="btn-group">
    <?
    echo $this->formSubmit($form->get('send'));
    ?>

</div>
</div>
<?php echo $this->form()->closeTag() ?>
