<h4>Копировать контент</h4>
<form id="contentsform" action="" method="POST" enctype="multipart/form-data">
    <table   class="table table-striped table-bordered table-hover typetable">
        <thead>
        <th>Название</th>
        <th>Значение</th>
        </thead>
        <tbody>
        <tr>
            <td>Название:</td>
            <td><input value="<?=$contents->name_contents;?>" class="varchartext" type="text" name="name_contents" /></td>
        </tr>
        <tr>
            <td>Alias:</td>
            <td><input value="<?=$contents->alias_contents;?>"  class="varchartext" type="text" name="alias_contents" /></td>
        </tr>
        <tr>
            <td colspan="2"><h5 align="center">Дополнительные поля</h5></td>
        </tr>
        <tr>
            <td>Брэнд:</td>
            <td><input class="varchartext" value="<?=$contents->name_brand;?>" type="text" name="name_brand" /></td>
        </tr>
        <tr>
            <td>Модель:</td>
            <td><input class="varchartext"  value="<?=$contents->name_model;?>"  type="text" name="name_model" /></td>
        </tr>
		<tr>
			<td>Цена:</td>
			<td><input class="integer" value="<?=$contents->money_contents;?>" type="text" name="money_contents" />
				<div class = "category_class">
					<?if($categoryBrand -> count() != 0):?>
						<table   class="table table-striped table-bordered table-hover typetable">
							<thead>
							<th>Название</th>
							<th>Значение</th>
							</thead>
							<tbody>
							<?foreach($categoryBrand as $g):?>
								<tr>
									<td><?=$g -> name_category;?></td>
									<td><input class = "integer" value="<?=$g->money_cb;?>" type="text" name="money_cb[<?=$g -> id_cb?>]" /></td>
								</tr>
							<?endforeach?>

							</tbody>
						</table>
					<?else:?>
						<b>Категорий нет</b>
					<?endif;?>
				</div>
			</td>
		</tr>
        <tr>
            <td>Гарантия:</td>
            <td><input class="varchartext" value="<?=$contents->warranty_contents;?>" type="text" name="warranty_contents" /></td>
        </tr>
        <tr>
            <td>Количество:</td>
            <td><input class="integer" value="<?=$contents->count_contents;?>" type="text" name="count_contents" /></td>
        </tr>
        <tr>
            <td>Меню:</td>
            <td>
                <select name="id_menu"  onchange="addMenuContent(this,event);" >>
                    <? foreach ($menu as $v): ?>
                        <?if($contents->id_menu==$v['id_menu']):?>
                            <option selected="selected" value="<?= $v['id_menu']; ?>"><?= $v['labelMenuTire']; ?></option>
                        <?else:?>
                            <option value="<?= $v['id_menu']; ?>"><?= $v['labelMenuTire']; ?></option>
                        <?endif;?>
                    <? endforeach; ?>
                </select>
            </td>
        </tr>
        </tbody>
    </table>
    <div id="addTemplateContent">

        <? foreach ($values as $v): ?>
            <table class="table table-striped table-bordered table-hover typetable">
                <thead>
                <th>Название</th>
                <th>Значение</th>
                </thead>
                <tbody>
                <tr>
                    <td><?= $v['name_type_field'] ?>:</td>
                    <td>
                        <?= $v['gen_field'] ?>
                    </td>
                </tr>
                </tbody>
            </table>
        <? endforeach; ?>
	    <div id="foto_block">
		    <?if($foto->count()!=0):?>
			    <?foreach($foto as $v):?>
				    <table class="table table-striped table-bordered table-hover table_my">
					    <tbody>
					    <tr>
						    <td>Фото</td>
						    <td>
							    <input class="foto_prev" value="<?=$v->name_foto?>" type="hidden"
							           name="foto[<?=$v->id_foto?>]"/>
							    <div class="one_foto">
								    <img onclick="window.open('/foto/original/<?=$v->name_foto?>',
									    'Фото resize',	'scrollbars=1,top=0,left=0,resizable=1,width=680,height=350');return false;"
								         class="img-polaroid" src="/foto/small/<?=$v->name_foto?>" />
							    </div>
						    </td>
						    <td><label class="radio">
								    <input value="<?=$v->id_foto?>" type="radio" value="<?=$v->id_foto?>"  name="main[]"
								           <?if(!empty($v->main_foto)):?>checked="checked"<?endif;?>  />
								    Основное фото
							    </label></td>
						    <td>
							    <button onclick="foto.del(this,event);return false;" class="btn">Удалить</button>
						    </td>
					    </tr>
					    </tbody>
				    </table>
			    <?endforeach;?>
		    <?endif;?>
	    </div>
	    <div id="file_block">
		    <?if($file->count()!=0):?>
			    <?foreach($file as $v):?>
				    <table class="table table-striped table-bordered table-hover table_my">
					    <tbody>
					    <tr>
						    <td>Файл</td>
						    <td>
							    <input class="foto_prev" value="<?=$v->url_file?>" type="hidden"  name="file[<?=$v->id_file?>]"/>
							    <div class="one_foto">
								    <a target="_blank" href="/file/<?=$v->url_file;?>">Скачать файл</a>
							    </div>
						    </td>
						    <td>
							    <input type="text" value="<?=$v->name_file?>" name="name_news_file_update[<?=$v->id_file?>]" />
						    </td>
						    <td>
							    <button onclick="file.del(this,event);return false;" class="btn">Удалить</button>
						    </td>
					    </tr>
					    </tbody>
				    </table>
			    <?endforeach;?>
		    <?endif;?>
	    </div>
	    <div class="button_block">
		    <div id="button_id_block" class="btn-group cent">
			    <input class="btn" type="submit" value="Сохранить" name="send" />
			    <input class="btn btn-inverse"  value="Добавить фото" type="button" onclick="foto.add();return false;" />
			    <input class="btn btn-success"  value="Добавить файл" type="button" onclick="file.add();return false;" />
		    </div>
	    </div>
    </div>

    </div>
</form>