<table   id="table_id_pere">
    <thead>
    <th>№</th>
    <th>Название</th>
    <th>Меню</th>
    <th>Показывается</th>
    <th>Дата создания(редактирования)</th>
	<th>Фото(Главное)</th>
    <th>Действие</th>
    </thead>
    </thead>
    <tbody>
    <? foreach ($contents as $v): ?>
        <tr>
            <td><?= $v->id_contents; ?></td>
            <td><?= $v->name_contents; ?></td>
            <td><?= $v->label_menu; ?></td>
	        <td><?= ($v->vis_contents == 1) ? "Да" : "Нет"; ?></td>
            <td><?= date("d.m.Y H:i:s",strtotime($v->datetime_create)); ?></td>
			<td>
				<?if(!empty($v -> foto_contents)):?>
				<img  src = "/foto/small/<?=$v -> foto_contents?>" />
				<?else:?>
				нет
				<?endif;?>
			</td>
            <td>
                <a title="Редактировать" href="/content/redactorContent/<?= $v->id_contents; ?>"><i class="icon-edit"></i>
                <a title="Удалить" onclick = "if(!confirm('Удалить?')) return false;"  href="/content/deleteContent/<?= $v->id_contents; ?>"><i class="icon-remove"></i>
                <a title="Копировать" href="/content/copyContent/<?= $v->id_contents; ?>"><i class="icon-plus-sign"></i>
            </td>
        </tr>
    <? endforeach; ?>
    </tbody>
</table>
</form>
<script>
    $(function(){
            $.extend($.tablesorter.themes.bootstrap, {
                table: 'table table-bordered',
                header: 'bootstrap-header'// give the header a gradient background
            });
            $("#table_id_pere").tablesorter({
                theme: "bootstrap",
                widthFixed : true,
                showProcessing: true,
                headerTemplate : '{content} {icon}',
                widgets: [ 'uitheme', 'zebra', 'filter']
            });

        }
    )
</script>

