<table   id="table_id_pere">
    <thead>
    <th>№</th>
    <th>Название</th>
    <th>Алиас</th>
    <th>Брэнд</th>
    <th>Сортировка</th>
    </thead>
    </thead>
    <tbody>
    <? foreach ($model as $v): ?>
        <tr onclick="location.href='/content/redactorModel/<?= $v->id_model; ?>'">
            <td><?= $v->id_model; ?></td>
            <td><?= $v->name_model; ?></td>
            <td><?= $v->alias_model; ?></td>
            <td><?= $v->name_brand; ?></td>
            <td><?= $v->order_model; ?></td>
        </tr>
    <? endforeach; ?>
    </tbody>
</table>
</form>
<script>
    $(function(){
            $.extend($.tablesorter.themes.bootstrap, {
                table: 'table table-bordered',
                header: 'bootstrap-header'// give the header a gradient background
            });
            $("#table_id_pere").tablesorter({
                theme: "bootstrap",
                widthFixed : true,
                showProcessing: true,
                headerTemplate : '{content} {icon}',
                widgets: [ 'uitheme', 'zebra', 'filter']
            });

        }
    )
</script>

