<table   id="table_id_pere">
    <thead>
    <th>№</th>
    <th>Название</th>
    <th>Алиас</th>
    <th>Сортировка</th>
	<th>Фото</th>
	<th>Действия</th>
    </thead>
    </thead>
    <tbody>
    <? foreach ($brand as $v): ?>
        <tr onclick="location.href='/content/redactorBrand/<?= $v->id_brand; ?>'">
            <td><?= $v->id_brand; ?></td>
            <td><?= $v->name_brand; ?></td>
            <td><?= $v->alias_brand; ?></td>
            <td><?= $v->order_brand; ?></td>
			<td>

				<?if(!empty($v->foto_brand)):?>
					<img style = "height: 60px;" src = "/foto/small/<?=$v->foto_brand;?>">
				<?endif;?>

			</td>
			<td>
				<a title="Редактировать" href="/content/redactorBrand/<?= $v->id_brand; ?>"><i class="icon-edit"></i>
				<a title="Удалить"  onclick = "if(!confirm('Удалить?')) return false;"   href="/content/deleteBrand/<?= $v->id_brand; ?>"><i class="icon-remove"></i>
			</td>
        </tr>
    <? endforeach; ?>
    </tbody>
</table>
</form>
<script>
    $(function(){
            $.extend($.tablesorter.themes.bootstrap, {
                table: 'table table-bordered',
                header: 'bootstrap-header'// give the header a gradient background
            });
            $("#table_id_pere").tablesorter({
                theme: "bootstrap",
                widthFixed : true,
                showProcessing: true,
                headerTemplate : '{content} {icon}',
                widgets: [ 'uitheme', 'zebra', 'filter']
            });

        }
    )
</script>

