<div id = "help">
	<table class="table table-striped table-bordered table-hover ">
		<thead>
		<tr><th>Название</th>
			<th>Значение</th>
			<th>Действие</th>
		</tr></thead>
		<tbody>
		<tr>
			<td>Категория</td>
			<td>
				<select  name="category[]">
					<option value="0">Не выбрано</option>
					<?foreach($category as $v):?>
						<option value="<?=$v -> id_category?>"><?=$v -> name_category?></option>
					<?endforeach?>
				</select>
			</td>
			<td>
				<button class = "btn" onclick="category.del(this)">Удалить</button>
			</td>
		</tr>
		</tbody>
	</table>
</div>
<h4>Редактировать брэнд</h4>
<?echo $this->form()->openTag($form);?>
<table class="table table-striped table-bordered table-hover typetable">
    <thead>
    <th>Название</th>
    <th>Значение</th>
    </thead>
    <tbody>
    <tr>
        <td>Название:</td>
        <td>
            <?
            $form->get('name_brand')->setValue("{$brand->name_brand}");
            echo $this->formInput($form->get('name_brand'));
            echo $this->formElementErrors($form->get('name_brand'));
            ?>
        </td>
    </tr>
    <tr>
        <td>Alias:</td>
        <td>
            <?
            $form->get('alias_brand')->setValue("{$brand->alias_brand}");
            echo $this->formInput($form->get('alias_brand'));
            echo $this->formElementErrors($form->get('alias_brand'));
            ?>
        </td>
    </tr>
	<tr>
		<td>Текст:</td>
		<td>
			<?
			$form->get('text_brand')->setValue("{$brand->text_brand}");
			echo $this->formInput($form->get('text_brand'));
			echo $this->formElementErrors($form->get('text_brand'));
			?>
		</td>
	</tr>
	<tr>
		<td>Фото:</td>
		<td>
			<?
			$form->get('foto_brand')->setValue($brand->foto_brand);
			echo $this->formFile($form->get('foto_brand'));
			?>
			<?if(!empty($brand->foto_brand)):?>
				<img style="width: 200px;" src='/foto/small/<?=$brand->foto_brand;?>' />
				<label><input name="del_foto" type="checkbox" />Удалить фото</label>
				<?if(!empty($brand->foto_brand)):?>
					<input type = "hidden" name = "foto_brand" value = "<?=$brand->foto_brand;?>" >
				<?endif?>
			 
			<?endif;?>

		</td>
	</tr>
    <tr>
        <td>Сортировка:</td>
        <td>
            <?
            $form->get('order_brand')->setValue("{$brand->order_brand}");
            echo $this->formInput($form->get('order_brand'));
            echo $this->formElementErrors($form->get('order_brand'));
            ?>
        </td>
    </tr>
    </tbody>
</table>

<div class = "category_block">
	<?if($categoryBrand -> count() != 0):?>
	<?foreach($categoryBrand as $v):?>

		<table class="table table-striped table-bordered table-hover ">
			<thead>
			<tr><th>Название</th>
				<th>Значение</th>
				<th>Действие</th>
			</tr></thead>
			<tbody>
			<tr>
				<td>Категория</td>
				<td>
					<select  name="category_set[<?=$v -> id_cb;?>]">
						<option value="0">Не выбрано</option>
						<?foreach($category as $w):?>
							<?if($v -> id_category == $w -> id_category):?>
								<option selected = "selected" value="<?=$w -> id_category?>"><?=$w -> name_category?></option>
							<?else:?>
								<option value="<?=$w -> id_category?>"><?=$w -> name_category?></option>
							<?endif;?>
						<?endforeach?>
					</select>
				</td>
				<td>
					<button class = "btn" onclick="category.del(this)">Удалить</button>
				</td>
			</tr>
			</tbody>
		</table>
	<?endforeach;?>
	<?endif;?>
</div>

<div class="button_block">
<div id="button_id_block" class="btn-group">
    <?
    echo $this->formSubmit($form->get('send'));
    ?>
    <?
    echo $this->formSubmit($form->get('del'));
    ?>
	<input type="button" value="Добавить категорию" class="btn" name="cat" onclick="category.add();">
</div>
</div>
<?php echo $this->form()->closeTag() ?>
