<h4>Редактировать контент</h4>
<form id="contentsform" action="" method="POST"  enctype="multipart/form-data">
	<div   id = "arh_category"></div>
    <table   class="table table-striped table-bordered table-hover typetable">
        <thead>
        <th>Название</th>
        <th>Значение</th>
        </thead>
        <tbody>
        <tr>
            <td>Название:</td>
            <td><input value="<?=htmlspecialchars($contents->name_contents);?>" class="varchartext" type="text" name="name_contents" /></td>
        </tr>
        <tr>
            <td>Alias:</td>
            <td><input value="<?=htmlspecialchars($contents->alias_contents);?>"  class="varchartext" type="text" name="alias_contents" /></td>
        </tr>
        <tr>
	        <td>Ссылка:</td>
	        <td><a target="_blank" href = "<?=$url;?>">Ссылка</a></td>
        </tr>
        <tr>
            <td colspan="2"><h5 align="center">Дополнительные поля</h5></td>
        </tr>
        <tr>
            <td>Брэнд:</td>
            <td><input class="varchartext" value="<?=$contents->name_brand;?>" type="text" name="name_brand" /></td>
        </tr>
        <tr>
            <td>Модель:</td>
            <td><input class="varchartext"  value="<?=$contents->name_model;?>"  type="text" name="name_model" /></td>
        </tr>
        <tr>
	    <td>Тип трансформации:</td>
	        <td>
		        <select name = "id_transform">
			        <option  value = "0">Не выбрано</option>
			        <?foreach($transform as $v):?>
				        <?if($contents -> id_transform == $v -> id_transform):?>
					        <option selected="selected" value = "<?=$v -> id_transform?>"><?=$v -> name_transform;?></option>
					    <?else:?>
					        <option value = "<?=$v -> id_transform?>"><?=$v -> name_transform;?></option>
					     <?endif;?>
			        <?endforeach;?>
		        </select>
	        </td>
        </tr>
		<tr>
			<td>Цена:</td>
			<td><input class="integer" value="<?=$contents->money_contents;?>" type="text" name="money_contents" />
				<div class = "category_class">
					<?if(!empty($categoryBrand)):?>
						<table   class="table table-striped table-bordered table-hover typetable">
							<thead>
							<th>Название</th>
							<th>Значение</th>
							</thead>
							<tbody>
							<?foreach($categoryBrand as $g):?>
								<tr>
									<td><?=$g -> name_category;?></td>
									<td><input class = "integer" value="<?=$g->money_cb;?>" type="text" name="money_cb[<?=$g -> id_cb?>]" /></td>
								</tr>
							<?endforeach?>

							</tbody>
						</table>
					<?else:?>
						<b>Категорий нет</b>
					<?endif;?>

				</div>
			</td>
		</tr>
        <tr>
	        <td colspan="2"><h5 align="center">SEO</h5></td>
        </tr>
        <tr>
	        <td>Description:</td>
	        <td><input class="varchartext" value="<?=$contents->description_contents;?>"  type="text"
	                   name="description_contents"/></td>
        </tr>
        <tr>
	        <td>Keywords:</td>
	        <td><input class="varchartext"  value="<?=$contents->keywords_contents;?>"  type="text"
	                   name="keywords_contents"/></td>
        </tr>
        <tr>
	        <td colspan="2"><h5 align="center">Меню</h5></td>
        </tr>

        <tr>
            <td>Меню:</td>
            <td>
                <select name="id_menu"  class = "chzn-select">
	                <option value = "0">- Не выбрано -</option>
                    <? foreach ($menu as $v): ?>
                        <?if($contents->id_menu==$v['id_menu']):?>
                            <option selected="selected" style = "padding-left:<?= $v['padding'];?>px" value="<?= $v['id_menu']; ?>"><?= $v['labelMenuTire']; ?></option>
                        <?else:?>
                            <option value="<?= $v['id_menu']; ?>" style = "padding-left:<?= $v['padding'];?>px" ><?= $v['labelMenuTire']; ?></option>
                        <?endif;?>
                    <? endforeach; ?>
                </select>
            </td>
        </tr>
        <tr>
	        <td>Шаблон:</td>
	        <td>
		        <select  name="id_type" onchange="addTemplateContent(this,event)" >
			        <option value = "0">- Не выбрано -</option>
			        <? foreach( $type as $v ): ?>
				        <?if($contents -> id_type == $v -> id_type):?>
					        <option selected="selected" value="<?= $v -> id_type; ?>"><?= $v -> name_type;?></option>
					    <?else:?>
					        <option  value="<?= $v -> id_type; ?>"><?= $v -> name_type;?></option>
					    <?endif;?>
			        <? endforeach; ?>
		        </select>
	        </td>
        </tr>
        </tbody>
    </table>
    <div id="addTemplateContent">

        <? foreach ($values as $v): ?>
            <table class="table table-striped table-bordered table-hover typetable">
                <thead>
                <th>Название</th>
                <th>Значение</th>
                </thead>
                <tbody>
                <tr>
                    <td><?= $v['name_type_field'] ?>:</td>
                    <td>
                        <?= $v['gen_field'] ?>
                    </td>
                </tr>
                </tbody>
            </table>
        <? endforeach; ?>
    </div>
	<div id="foto_block">
		<?if($foto->count()!=0):?>
			<?foreach($foto as $v):?>
				<table class="table table-striped table-bordered table-hover table_my">
					<tbody>
					<tr>
						<td>Фото</td>
						<td>
							<input class="foto_prev" value="<?=$v->name_foto?>" type="hidden"
							       name="foto2[<?=$v->id_foto?>]"/>
							<div class="one_foto">
								<img onclick="window.open('/foto/original/<?=$v->name_foto?>',
									'Фото resize',	'scrollbars=1,top=0,left=0,resizable=1,width=680,height=350');return false;"
								     class="img-polaroid" src="/foto/small/<?=$v->name_foto?>" />
							</div>
						</td>
						<td><label class="radio">
								<input value="<?=$v->id_foto?>" type="radio" value="<?=$v->id_foto?>"  name="main[]"
								       <?if(!empty($v->main_foto)):?>checked="checked"<?endif;?>  />
								Основное фото
							</label></td>
						<td>
							<button onclick="foto.del(this,event);return false;" class="btn">Удалить</button>
						</td>
					</tr>
					</tbody>
				</table>
			<?endforeach;?>
		<?endif;?>
	</div>
	<div id="file_block">
		<?if($file->count()!=0):?>
			<?foreach($file as $v):?>
				<table class="table table-striped table-bordered table-hover table_my">
					<tbody>
					<tr>
						<td>Файл</td>
						<td>
							<input class="foto_prev" value="<?=$v->url_file?>" type="hidden"  name="file[<?=$v->id_file?>]"/>
							<div class="one_foto">
								<a target="_blank" href="/file/<?=$v->url_file;?>">Скачать файл</a>
							</div>
						</td>
						<td>
							<input type="text" value="<?=$v->name_file?>" name="name_news_file_update[<?=$v->id_file?>]" />
						</td>
						<td>
							<button onclick="file.del(this,event);return false;" class="btn">Удалить</button>
						</td>
					</tr>
					</tbody>
				</table>
			<?endforeach;?>
		<?endif;?>
	</div>

	<table class="table table-striped table-bordered table-hover typetable">
		<thead>
		<th>Название</th>
		<th>Значение</th>
		</thead>
		<tbody>
		<tr>
			<td>Показать:</td>
			<td>
				<?if($contents -> vis_contents):?>
					<input   checked="checked"  type="checkbox" name="vis_contents"/>
				<?else:?>
					<input type="checkbox" name="vis_contents"/>
				<?endif;?>
			</td>
		</tr>
		</tbody>
	</table>
	    <div class="button_block">
		    <div id="button_id_block" class="btn-group cent">
			    <input class="btn" type="submit" value="Сохранить" name="send" />
			    <input class="btn" type="submit" value="Удалить" name="del" />
			    <input class="btn btn-inverse"  value="Добавить фото" type="button" onclick="foto.add();return false;" />
			    <input class="btn btn-inverse"  value="Добавить фото с URL" type="button" onclick="foto.addUrl();return false;" />
			    <input class="btn btn-success"  value="Добавить файл" type="button" onclick="file.add();return false;" />
		    </div>
	    </div>
    </div>
</form>