<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default panel-shadow" data-collapsed="0">
            <!-- to apply shadow add class "panel-shadow" -->
            <!-- panel head -->
            <div class="panel-heading">
                <div class="panel-title">
                    <?=$article->getTitle();?>
                    <small>
                        <?=$article->getDateTime()->format('d.m.Y');?>
                    </small>
                </div>
                <div class="panel-options"><a href="#sample-modal"
                                              data-toggle="modal"
                                              data-target="#sample-modal-dialog-3"
                                              class="bg"><i
                                class="entypo-cog"></i></a>
                    <a href="#" data-rel="collapse"><i
                                class="entypo-down-open"></i></a>
                    <a href="#" data-rel="reload"><i
                                class="entypo-arrows-ccw"></i></a>
                    <a href="#" data-rel="close"><i
                                class="entypo-cancel"></i></a>
                </div>
            </div> <!-- panel body -->
            <div class="panel-body">

                <?=$article->getText();?>

            </div>
        </div>
    </div>
</div>
