<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default panel-shadow" data-collapsed="0">
            <!-- to apply shadow add class "panel-shadow" -->
            <!-- panel head -->
            <div class="panel-heading">
                <div class="panel-title">
                    <?=$article->getTitle();?>
                    <small>
                        <?=$article->getDateTime()->format('d.m.Y');?>
                    </small>
                </div>
                <div class="panel-options"><a href="#sample-modal"
                                              data-toggle="modal"
                                              data-target="#sample-modal-dialog-3"
                                              class="bg"><i
                                class="entypo-cog"></i></a>
                    <a href="#" data-rel="collapse"><i
                                class="entypo-down-open"></i></a>
                    <a href="#" data-rel="reload"><i
                                class="entypo-arrows-ccw"></i></a>
                    <a href="#" data-rel="close"><i
                                class="entypo-cancel"></i></a>
                </div>
            </div> <!-- panel body -->
            <div class="panel-body">

                <?=$article->getText();?>

            </div>
        </div>
    </div>
</div>

<script src="http://demo.neontheme.com/assets/js/gsap/TweenMax.min.js"
        id="script-resource-1"></script>
<script src="http://demo.neontheme.com/assets/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js"
        id="script-resource-2"></script>
<script src="http://demo.neontheme.com/assets/js/bootstrap.js"
        id="script-resource-3"></script>
<script src="http://demo.neontheme.com/assets/js/joinable.js"
        id="script-resource-4"></script>
<script src="http://demo.neontheme.com/assets/js/resizeable.js"
        id="script-resource-5"></script>
<script src="http://demo.neontheme.com/assets/js/neon-api.js"
        id="script-resource-6"></script>
<script src="http://demo.neontheme.com/assets/js/cookies.min.js"
        id="script-resource-7"></script>
<script src="http://demo.neontheme.com/assets/js/neon-chat.js"
        id="script-resource-8"></script> <!-- JavaScripts initializations and stuff -->
<script src="http://demo.neontheme.com/assets/js/neon-custom.js"
        id="script-resource-9"></script> <!-- Demo Settings -->
<script src="http://demo.neontheme.com/assets/js/neon-demo.js"
        id="script-resource-10"></script>
<script src="http://demo.neontheme.com/assets/js/neon-skins.js"
        id="script-resource-11"></script>