<?php $partial = array('layout/breadcrumbs.phtml', 'default') ?>
<?php $this->navigation('NavigationDynamic')->breadcrumbs()->setPartial(
    $partial
) ?>
<?php echo $this->navigation('NavigationDynamic')->breadcrumbs()->render() ?>
<?
unset($params['page']);

?>
    <h1>Авторы</h1>
    <?if(count($paginator)):?>
    <div class="posts-list-4-cols">
        <?foreach ($paginator as $author): ?>
            <? $params['alias_menu'] = $author->getAlias(); ?>
            <a href="<?= $this->url(
                'home/authors/one',
                $params
            ); ?>">
                <?= $author->getName(); ?>
            </a>
        <? endforeach; ?>

    </div>
    <div class="text-center">
        <?
        echo $this->paginationControl(
            null,
            null,
            'pagination_authors',
            array(
                'route' => $route,
                'action' => $params['action'],
            )
        ); ?>


    </div>
    <?endif;?>
<? if ($menu->getSeoText()): ?>
    <blockquote class="blockquote-default">
        <p>
            <small><?=$menu->getSeoText(); ?></small>
        </p>
    </blockquote>
<? endif; ?>