<?php  $partial = array('layout/breadcrumbs.phtml', 'default') ?>
<?php $this->navigation('NavigationDynamic')->breadcrumbs()->setPartial($partial) ?>
<?php echo $this->navigation('NavigationDynamic')->breadcrumbs()->render() ?>

<?$t = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$params = $t->getParams();
$route = $t->getMatchedRouteName();
unset($params['page']);

?>
<h1>Авторы</h1>

<div class="posts-list-4-cols row">
	<ul>
<?foreach($authors as $k => $v):?>
		<?$params['alias_menu'] = $v->alias;?>
		<li><a  href="<?=$this->url('home/authors/one', $params);?>"><?=$v->name;?></a></li>
<?endforeach;?>
	</ul>
</div>

<div class = "text-center">
<?
echo $this->paginationControl($authors, 'Sliding', 'pagination_authors',
	array(
		'route' => $route,
		'action'=>$params['action'],
		'subdomain'=>$params['subdomain'],
	)); ?>


</div>

<?if(!empty($menu->seo_text)):?>
	<blockquote class="blockquote-default">
		<p>
			<small><?=$menu->seo_text;?></small>
		</p>
	</blockquote>
<?endif;?>