<?php
/** @var $book \Application\Entity\Book */
?>
<?unset($params['page']);?>
<div class="book_cl" data-url="<?= $this->url($route, $params); ?>">
    <article class="album">
        <header class="bf">
            <? $params['book'] = $book->getAlias(); ?>
            <a href="<?= $this->url($route, $params); ?>">
                    <img class="img-thumbnail"
                         src="<? echo IMAGE_URL?>/resize/200/<?= $book->getFoto(); ?>">
            </a>
            <?php echo $this->partial(
                'application/index/stars',
                [
                    'id_book'     => $book->getId(),
                    'aver_value'  => $book->getStars(),
                    'count_stars' => $book->getCountStars(),
                ]
            ); ?>
        </header>
        <section class="album-info">
            <h3><a href="<?= $this->url(
                    $route,
                    $params
                ); ?>"><?= $book->getName(); ?>
                </a>
                    <?
                    $link = '<a href="'.$this->url('home/admin-book',['action' => 'edit', 'id' => $book->getId()]).'">
                                 <i class="glyphicon glyphicon-edit"></i>
                            </a>
                    ';
                    ?>
                <?=$this->button()->changeBook($link);?>
            </h3>
            <ul class="no-list-style">
                <?
                $params['alias_menu'] = $book->getNAliasMenu();
                $params['action'] = 'one_genre';
                $params['s'] = $book->getNS();
                ?>

                <li>Жанр: <?= $book->getNameZhanr(); ?></li>
                <li>Страниц: <span><?= $book->getKolStr(); ?></span></li>
                <li>Язык: <span><?= $book->getLang(); ?></span></li>
                <?if(!empty($book->getYear())):?>
                    <li>Год: <span><?= $book->getYear(); ?></span></li>
                <?endif;?>
                <? if(count($book->getAvtor())):?>
                    <li>Автор:
                    <?foreach($book->getAvtor() as $item => $avtor):?>
                        <? if ($item > 2) {
                            break;
                        } ?>
                        <?= $avtor->getName(); ?> /
                    <?endforeach;?>
                    </li>
                <?endif;?>
                <? if (count($book->getFiles()) != 0): ?>
                    <li>
                        <? foreach ($book->getFiles() as $file): ?>
                            <? /** @var $file \Application\Entity\BookFiles */ ?>
                            <button rel="nofollow" class="btn btn-sm btn-success"
                                    onclick="download_file.get_files(event, this, '<?= $this->url(
                                        'home/download',
                                        ['id_book_files' => $file->getIdBookFiles()]
                                    ); ?>')"
                            >
                                <?= $file->getType(); ?>
                            </button>
                        <? endforeach; ?>
                    </li>
                <? endif; ?>
            </ul>
            <?
            if (!empty(trim($book->getTextSmall()))): ?>
                <button class="btn btn-white" data-toggle="popover"
                        data-trigger="click" data-placement="top"
                        data-content="<?= htmlspecialchars(
                            strip_tags($book->getTextSmall())
                        ); ?> " data-original-title="Анонс">Краткое
                    содержание
                </button>
            <? endif; ?>
        </section>
        <footer>
            <div class="album-images-count">
                <div class="text-right">
                    <i class="entypo-eye"></i>
                    <?= $book->getVisit(); ?>
                    <i class="entypo-calendar"></i>
                    <?= $book->getDateAdd()->format('d.m.Y'); ?>
                </div>
            </div>
        </footer>
    </article>
</div>
