<div class="book_cl" data-url = "<?=$this->url($route, $params);?>" >
    <article class="album">
        <header class = "bf">
            <?$params['book'] = $v->alias;?>
            <a href="<?=$this->url($route, $params);?>">
                <?if(stristr($v->foto, "\n") or empty($v->foto)):?>
                    <img  class="img-thumbnail" src="/templates/newimg/small/nofoto.jpg">
                <?else:?>
                    <img  class="img-thumbnail" src="/templates/newimg/small/<?=$v->foto;?>">
                <?endif;?>
            </a>
            <?php echo $this->partial('application/index/stars', ['id_book' => $v->id, 'aver_value' => $v->stars, 'count_stars' => $v->count_stars]);?>
        </header>
        <section class="album-info">
            <h3><a href="<?=$this->url($route, $params);?>"><?=$v->name;?></a></h3>
            <ul class = "no-list-style">
                <?
                $params['alias_menu'] = $v->n_alias_menu;
                $params['action'] = 'one_genre';
                $params['s'] = $v->n_s;
                ?>

                <li>Жанр: <a href = "<?=$this->url('home/genre/one', $params);?>"><?=$v->name_zhanr;?></a></li>
                <li>Страниц: <span><?=$v->kol_str;?></span></li>
                <li>Язык: <span><?=$v->lang;?></span></li>
            </ul>
            <?if(!empty(trim($v->text_small))):?>
                <button class="btn btn-white" data-toggle="popover" data-trigger="click" data-placement="top" data-content="<?=htmlspecialchars($v->text_small);?> " data-original-title="Анонс">Краткое содержание</button>
            <?endif;?>
        </section>
        <footer>
            <div class="album-images-count">
                <div class = "text-right">
                    <i class="entypo-eye"></i>
                    <?=$v->visit;?>
                    <i class="entypo-calendar"></i>
                    <?=date('d.m.Y', strtotime($v->date_add));?>
                </div>
            </div>
        </footer>
    </article>
</div>

<?
global $count_view, $rand, $rand1, $rand2;

if($count_view == null){
    $count_view = 0;
    $rand = rand(4,6);
    $rand1 = rand(11,13);
    $rand2 = rand(22,24);
}
$count_view++;

if(in_array($count_view,[$rand, $rand1, $rand2])){?>
<div class="book_cl no-padding"  >
    <article class="album">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <ins class="adsbygoogle"
             style="display:block;width: 100%;"
             data-ad-format="fluid"
             data-ad-layout-key="-ao-1c-3k-8v+14f"
             data-ad-client="ca-pub-2745956118385780"
             data-ad-slot="8980418046"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </article>
</div>

<?
}

