<?php $partial = [
    'layout/breadcrumbs.phtml',
    'default',
] ?>
<?php $this->navigation('NavigationDynamic')->breadcrumbs()->setPartial(
    $partial
) ?>
<?php echo $this->navigation('NavigationDynamic')->breadcrumbs()->render() ?>

<? $t = $this->getHelperPluginManager()
    ->getServiceLocator()
    ->get('Application')
    ->getMvcEvent()
    ->getRouteMatch();
$params = $t->getParams();
$route = $t->getMatchedRouteName();
unset($params['page']);

$user = $this->getHelperPluginManager()->getServiceLocator()->get('User');
?>

<div itemscope itemtype="http://schema.org/Book"
     itemid="https://www.booklot.ru<?= $_SERVER['REQUEST_URI']; ?>">
    <link itemprop="additionalType" href="http://schema.org/Product"/>
    <h1 itemprop="name">
        <?= $title; ?>
        <?if(!empty($user) and $user->getRole() == 'admin'):?>
            <a href = "<?=$this->url('home/admin-book', ['action' => 'edit', 'id' => $book['id']])?>">
                <i class="glyphicon glyphicon-edit"></i>
            </a>
        <?endif;?>
    </h1>
    <? if (!empty(trim($book['text_small']))): ?>
        <div itemprop="description">
            <?= strip_tags($book['text_small'], ''); ?>
        </div>
    <? else: ?>
        <div itemprop="description">
            Описание отсутствует
        </div>
    <? endif; ?>
    <div class="profile-env">

        <header class="row">

            <div class="col-sm-2">

                <a href="/templates/newimg/full/<?= $book['foto']; ?>"
                   class="profile-picture">
                    <? if (stristr($book['foto'], "\n")
                        or empty($book['foto'])
                    ): ?>
                        <img itemprop="image"
                             src="/templates/newimg/full/nofoto.jpg"
                             class="img-responsive"/>
                    <? else: ?>
                        <img itemprop="image"
                             src="/templates/newimg/full/<?= $book['foto']; ?>"
                             class="img-responsive"/>
                    <? endif; ?>
                </a>

            </div>

            <div class="col-sm-10">

                <ul class="profile-info-sections">
                    <? if ($count_text): ?>
                        <li>
                            <div class="profile-name">
                                <strong>
                                    <h2><a href="read/1/"><?= $book['name']; ?>
                                            Онлайн</a>
                                        <a href="read/1/"
                                           class="user-status is-online tooltip-primary"
                                           data-toggle="tooltip"
                                           data-placement="top"
                                           data-original-title="Читать"></a>
                                    </h2>
                                    <!-- User statuses available classes "is-online", "is-offline", "is-idle", "is-busy" -->
                                </strong> <span><a
                                            href="read/1/">Читать <?= $book['name']; ?></a></span>
                            </div>
                        </li>
                    <? endif; ?>
                    <li>
                        <div class="profile-stat">
                            <h3><?= $book['visit']; ?></h3>
                            <span>Просмотр(ов)</span>
                        </div>
                    </li>
                </ul>
                <div class="row">
                    <div class="col-sm-12">
                        <script async
                                src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                        <!-- book_white_center -->
                        <ins class="adsbygoogle" style="display:block"
                             data-ad-client="ca-pub-2745956118385780"
                             data-ad-slot="9524354974"
                             data-ad-format="auto"></ins>
                        <script>
                            (adsbygoogle = window.adsbygoogle || []).push({});
                        </script>
                    </div>
                </div>
            </div>
        </header>
        <section class="profile-info-tabs">
            <div class="row">
                <div class="col-sm-offset-2 col-sm-3">
                    <ul class="user-details">
                        <? if (isset($bookRoute['name'])
                            and !empty($bookRoute['name'])
                        ): ?>
                            <li>
                                <i class="entypo-doc-text-inv"></i> Жанр:
                                <a itemprop="genre" href="<?= $this->url(
                                    'home/genre/one',
                                    [
                                        'alias_menu' => $bookRoute['alias_menu'],
                                        's'          => $bookRoute['s'],

                                    ]
                                ); ?>"><?= $bookRoute['name']; ?></a>
                            </li>
                        <? endif; ?>



                        <? if ($avtor->count() != 0): ?>
                            <li>
                                <i class="entypo-user"></i> Автор: /
                                <? foreach ($avtor as $v):
                                    ?><? $ar = $v->arr; ?>
                                    <a itemprop="author" href="<?= $this->url(
                                        'home/authors/one',
                                        [
                                            'alias_menu' => $v->alias,
                                        ]
                                    ); ?>"><?= $ar['name']; ?></a> /
                                <? endforeach; ?>
                            </li>
                        <? endif; ?>
                        <? if ($serii->count() != 0): ?>
                            <li>
                                <i class="entypo-layout"></i> Серия:
                                <? foreach ($serii as $v):
                                    ?><? $ar = $v->arr; ?>
                                    <a href="<?= $this->url(
                                        'home/series/one',
                                        [
                                            'alias_menu' => $v->alias,
                                        ]
                                    ); ?>"><?= $ar['name']; ?></a>
                                <? endforeach; ?>
                            </li>
                        <? endif; ?>
                        <? if ($translit->count() != 0): ?>
                            <li>
                                <i class="entypo-user"></i> Переводчик: / <?
                                foreach ($translit as $v):
                                    ?><? $ar = $v->arr; ?>
                                    <a href="<?= $this->url(
                                        'home/translit/one',
                                        [
                                            'alias_menu' => $v->alias,
                                        ]
                                    ); ?>"><?= $ar['name']; ?></a> /
                                <? endforeach; ?>
                            </li>
                        <? endif; ?>
                        <? if ($book['kol_str']): ?>
                            <li>
                                <i class="entypo-pencil"></i> Количество
                                страниц:
                                <span itemprop="numberOfPages"><?= $book['kol_str']; ?></span>
                            </li>
                        <? endif; ?>

                        <? if ($book['lang']): ?>
                            <li>
                                <i class="entypo-language"></i> Язык книги:
                                <span itemprop="inLanguage"><?= $book['lang']; ?></span>
                            </li>
                        <? endif; ?>

                        <? if ($book['year']): ?>
                            <li>
                                <i class="entypo-calendar"></i> Год:
                                <span itemprop="copyrightYear"><?= $book['year']; ?></span>
                            </li>
                        <? endif; ?>

                        <? if ($book['city']): ?>
                            <li>
                                <i class="entypo-globe"></i> Город
                                печати: <?= $book['city']; ?>
                            </li>
                        <? endif; ?>
                    </ul>
                </div>
                <div class="col-sm-offset-1 col-sm-6" itemprop="aggregateRating"
                     itemscope="itemscope" itemtype="http://schema.org/AggregateRating">
                    <meta content="<?=$book['stars'];?>" itemprop="ratingValue">
                    <meta content="<?=$book['count_stars'];?>" itemprop="ratingCount">
                    <?php echo $this->partial(
                        'application/index/stars',
                        [
                            'id_book'     => $book['id'],
                            'aver_value'  => $book['stars'],
                            'count_stars' => $book['count_stars'],
                        ]
                    ); ?>
                </div>
            </div>
            <ul class="nav nav-tabs tabs-book">
                <li class="active"><a data-toggle="tab"
                                      href="#comm">Комментарии</a></li>
                <li><a data-toggle="tab" href="#download">Файлы для
                        скачивания</a></li>
                <? if ($soder->count() != 0): ?>
                    <li><a data-toggle="tab" href="#soder">Содержание</a></li>
                <? endif; ?>
                <? if (count($similar) != 0): ?>
                    <li><a data-toggle="tab" href="#similar">Схожие книги</a>
                    </li>
                <? endif; ?>
            </ul>
        </section>
        <div class="tab-content">
            <div class="tab-pane active" id="comm">
                <section class="profile-feed">
                    <?php echo $this->partial(
                        'application/cabinet/my_library_button',
                        ['book' => $book]
                    ); ?>
                    <?php echo $this->partial(
                        'application/index/comments',
                        ['book' => $book]
                    ); ?>
                    <div class="profile-stories">
                        <article class="story">
                            <div class="story-content">
                                <footer>
                                    <script type="text/javascript">
                                        VK.init({
                                            apiId: 2786799,
                                            onlyWidgets: true
                                        });
                                    </script>

                                    <h5 class="text-left">Комментарии с других
                                        ресурсов:</h5>
                                    <div id="vk_comments"
                                         class="margin-button"></div>
                                    <script type="text/javascript">
                                        VK.Widgets.Comments("vk_comments", {
                                            limit: 10,
                                            width: "auto",
                                            attach: "*"
                                        });
                                    </script>
                                    <? if ($comments_faik->count() != 0): ?>

                                        <ul class="comments">
                                            <? foreach ($comments_faik as $v):
                                                ?>
                                                <li>
                                                    <? $ar = $v->arr; ?>
                                                    <div class="user-comment-thumb">
                                                        <img src="/templates/newimg/original/<?= $ar['foto']; ?>"
                                                             alt="<?= $ar['user']; ?>"
                                                             class="img"
                                                             width="70"/>
                                                    </div>
                                                    <div class="user-comment-content">
                                                        <a href="#"
                                                           class="user-comment-name">
                                                            <?= $ar['user']; ?>
                                                        </a>
                                                        <?= strip_tags(
                                                            $ar['text'],
                                                            '<img><p><br>'
                                                        ); ?>
                                                    </div>
                                                </li>
                                            <? endforeach; ?>
                                        </ul>
                                    <? endif; ?>
                                </footer>
                            </div>
                        </article>
                    </div>
                </section>
            </div>
            <div class="tab-pane" id="download">
                <? if ($files->count() != 0): ?>
                    Данную книгу  "<?= $book['name']; ?>" в онлайн вы сможете
                    <b>скачать
                        бесплатно</b> с нашего сайта в следущих по порядку форматах:

                    <div class="bs-example">
                        <div class="btn-group dropdown">
                            <button type="button" class="btn btn-danger">
                                Download
                            </button>
                            <button type="button"
                                    class="btn btn-danger dropdown-toggle"
                                    data-toggle="dropdown"><i
                                        class="entypo-down"></i>
                            </button>

                            <ul class="dropdown-menu dropdown-danger"
                                role="menu">
                                <? foreach ($files as $v):
                                    ?><? $ar = $v->arr; ?>
                                    <li>
                                        <a href="/templates/newsave/<?= $v->type ?>/<?= $v->name ?>.zip"><i
                                                    class="entypo-right"></i><?= $ar['type']; ?>
                                            Format</a></li>
                                <? endforeach; ?>
                            </ul>
                        </div>
                    </div>
                <? else: ?>
                    Извините, но у данной книги нет файлов.
                <? endif; ?>
            </div>
            <? if ($soder->count() != 0): ?>
                <div class="tab-pane" id="soder">

                    <h3>Оглавление книги <?= $book['name']; ?></h3>
                    <ul>
                        <? foreach ($soder as $v):
                            ?><? $ar = $v->arr; ?><? $params['content']
                            = $v->alias; ?>
                            <li>
                                <a href="<?= $this->url(
                                    $route_similar.'/content',
                                    $params
                                ); ?>"><?= $ar['name'] ?></a>
                            </li>
                        <? endforeach; ?>
                    </ul>
                </div>
            <? endif; ?>
            <? if (count($similar) != 0): ?>
                <div class="tab-pane" id="similar">

                    <div class="posts-list-4-cols">
                        <? foreach ($similar as $v1): ?><?
                            $params_similar = $params;
                            unset($params_similar['content']);
                            $params_similar['book'] = $v1->book_alias;
                            ?>
                            <div class="book_cl">
                                <article class="album">
                                    <header class="bf">
                                        <a href="<?= $this->url(
                                            $route_similar,
                                            $params_similar
                                        ); ?>">
                                            <? if (stristr($v1->foto, "\n")
                                                or empty($v1->foto)
                                            ): ?>
                                                <img class="img-thumbnail"
                                                     src="/templates/newimg/small/nofoto.jpg">
                                            <? else: ?>
                                                <img class="img-thumbnail"
                                                     src="/templates/newimg/small/<?= $v1->foto; ?>">
                                            <? endif; ?>
                                        </a>
                                    </header>
                                    <section class="album-info">
                                        <h3>
                                            <a href="<?= $this->url(
                                                $route_similar,
                                                $params_similar
                                            ); ?>"><?= $v1->book_name; ?></a>
                                        </h3>
                                    </section>
                                </article>
                            </div>
                        <? endforeach; ?>
                    </div>
                </div>
            <? endif; ?>
        </div>
    </div>
</div>