<?php
/** @var \Application\Entity\Book $book */
/** @var $route_similar */
/** @var $problem_avtor */
?>
<?php $partial = [
    'layout/breadcrumbs.phtml',
    'default',
]; ?>
<?php   $this->navigation('NavigationDynamic')->breadcrumbs()->setPartial(
    $partial
);  ?>
<?php   echo $this->navigation('NavigationDynamic')->breadcrumbs()->render() ?>

<?
unset($params['page']);
?>

<?if($problem_avtor):?>
<div class="alert alert-warning">
    Данная книга заблокирована правообладателем(либо Роскомнадзор-ом).
</div>
<?else:?>
    <?=$this->permission()->zhanrOld($book->getMenu()->getOld());?>
<div itemscope itemtype="http://schema.org/Book"
     itemid="https://www.booklot.org<?= $_SERVER['REQUEST_URI']; ?>">
    <link itemprop="additionalType" href="http://schema.org/Product"/>
    <h1 itemprop="name">
        <?= $title; ?>
        <?
        $link = '<a href = "'.$this->url('home/admin-book', ['action' => 'edit', 'id' => $book->getId()]).'">
                <i class="glyphicon glyphicon-edit"></i>
            </a>';
        ?>
        <?=$this->button()->changeBook($link);?>
    </h1>
    <? if (!empty(trim($book->getTextSmall()))): ?>
        <div itemprop="description">
            <?= strip_tags($book->getTextSmall(), ''); ?>
        </div>
    <? else: ?>
        <div itemprop="description">
            Описание отсутствует
        </div>
    <? endif; ?>
    <div class="profile-env">
        <header class="row">
            <div class="col-sm-2">
                <a href="<?=IMAGE_URL?>/<?= $book->getFoto(); ?>"
                   class="profile-picture">
                        <img itemprop="image"
                             src="<?=IMAGE_URL?>/resize/200/<?= $book->getFoto(); ?>"
                             class="img-responsive"/>
                </a>
            </div>
            <div class="col-sm-10">
                <ul class="profile-info-sections">
                     <? if (count($book->getText()) != 0): ?>
                        <li>
                            <div class="profile-name">
                                <strong>
                                    <?if($problem_avtor):?>
                                        <h2>
                                            <?= $book->getName(); ?>
                                                Онлайн
                                            <a href="#"
                                               class="user-status is-offline tooltip-primary"
                                               data-toggle="tooltip"
                                               data-placement="top"
                                               data-original-title="Читать"></a>
                                        </h2>
                                    <?else:?>
                                        <h2>
                                            <a href="read/1/"><?= $book->getName(); ?>
                                                Онлайн</a>
                                            <a href="read/1/"
                                               class="user-status is-online tooltip-primary"
                                               data-toggle="tooltip"
                                               data-placement="top"
                                               data-original-title="Читать"></a>
                                        </h2>
                                    <?endif;?>
                                </strong>
                                <?if(!$problem_avtor):?>
                                <span>
                                    <a href="read/1/">
                                        Читать <?= $book->getName(); ?>
                                    </a>
                                </span>
                                <?endif;?>
                            </div>
                        </li>
                    <? endif; ?>
                    <li>
                        <div class="profile-stat">
                            <h3><?= $book->getVisit(); ?></h3>
                            <span>Просмотр(ов)</span>
                        </div>
                    </li>
                </ul>
                <?=$this->ad()->name('content1');?>
            </div>
        </header>
        <section class="profile-info-tabs">
            <div class="row">
                <div class="col-sm-offset-2 col-sm-3">
                    <ul class="user-details">
                            <li>
                                <i class="entypo-doc-text-inv"></i> Жанр:
                                <a itemprop="genre" href="<?= $this->url(
                                    'home/genre/one',
                                    [
                                        'alias_menu' => $book->getNAliasMenu(),
                                        's'          => $book->getNS(),

                                    ]
                                ); ?>">
                                    <?= $book->getNameZhanr(); ?>
                                </a>
                            </li>
                        <? if (count($book->getAvtor()) != 0): ?>
                            <li>
                                <i class="entypo-user"></i> Автор: /
                                <? foreach ($book->getAvtor() as $avtor):?>
                                    <?/** @var $avtor \Application\Entity\MAvtor */?>
                                    <a itemprop="author" href="<?= $this->url(
                                        'home/authors/one',
                                        [
                                            'alias_menu' => $avtor->getAlias(),
                                        ]
                                    ); ?>"><?= $avtor->getName(); ?></a> /
                                <? endforeach; ?>
                            </li>
                        <? endif; ?>
                        <? if (count($book->getSerii()) != 0): ?>
                            <li>
                                <i class="entypo-layout"></i> Серия:
                                <? foreach ($book->getSerii() as $serii): ?>
                                    <?/** @var $serii \Application\Entity\MSerii */?>
                                    <a href="<?= $this->url(
                                        'home/series/one',
                                        [
                                            'alias_menu' => $serii->getAlias(),
                                        ]
                                    ); ?>">
                                        <?= $serii->getName(); ?>
                                    </a>
                                <? endforeach; ?>
                            </li>
                        <? endif; ?>
                        <? if (count($book->getTranslit()) != 0): ?>
                            <li>
                                <i class="entypo-user"></i> Переводчик: / <?
                                foreach ($book->getTranslit() as $translit):?>
                                    <?/** @var $translit \Application\Entity\MTranslit */?>
                                    <a href="<?= $this->url(
                                        'home/translit/one',
                                        [
                                            'alias_menu' => $translit->getAlias(),
                                        ]
                                    ); ?>">
                                        <?= $translit->getName(); ?>
                                    </a> /
                                <? endforeach; ?>
                            </li>
                        <? endif; ?>
                        <? if ($book->getKolStr()): ?>
                            <li>
                                <i class="entypo-pencil"></i> Количество
                                страниц:
                                <span itemprop="numberOfPages"><?= $book->getKolStr(); ?></span>
                            </li>
                        <? endif; ?>
                        <? if ($book->getLang()): ?>
                            <li>
                                <i class="entypo-language"></i> Язык книги:
                                <span itemprop="inLanguage"><?= $book->getLang(); ?></span>
                            </li>
                        <? endif; ?>
                        <? if ($book->getYear()): ?>
                            <li>
                                <i class="entypo-calendar"></i> Год:
                                <span itemprop="copyrightYear"><?= $book->getYear(); ?></span>
                            </li>
                        <? endif; ?>
                        <? if ($book->getCity()): ?>
                            <li>
                                <i class="entypo-globe"></i> Город
                                печати: <?= $book->getCity(); ?>
                            </li>
                        <? endif; ?>
                    </ul>
                </div>
                    <?if($book->getStars() and $book->getCountStars()):?>
                    <div class="col-sm-offset-1 col-sm-6" itemprop="aggregateRating"
                         itemscope="itemscope" itemtype="http://schema.org/AggregateRating">
                    <meta content="<?=$book->getStars();?>" itemprop="ratingValue">
                    <meta content="<?=$book->getCountStars();?>" itemprop="ratingCount">
                    <meta content="<?=$book->getCountStars();?>" itemprop="reviewCount">
                        <?else:?>
                        <div class="col-sm-offset-1 col-sm-6">
                    <?endif;?>
                    <?php echo $this->partial(
                        'application/index/stars',
                        [
                            'id_book'     => $book->getId(),
                            'aver_value'  => $book->getStars(),
                            'count_stars' => $book->getCountStars(),
                        ]
                    ); ?>
                </div>
            </div>
            <ul class="nav nav-tabs tabs-book">
                <li class="active"><a data-toggle="tab" href="#comm">Комментарии</a>
                </li>
                <?if(!$problem_avtor):?>
                <li>
                    <a data-toggle="tab" href="#download">
                        Файлы для скачивания
                    </a>
                </li>
                <? endif; ?>
                <? if ($problem_avtor == 0 and count($book->getSoder()) != 0): ?>
                    <li><a data-toggle="tab" href="#soder">Содержание</a></li>
                <? endif; ?>
                <? if ($problem_avtor == 0 and count($similar) != 0): ?>
                    <li><a data-toggle="tab" href="#similar">Схожие книги</a>
                    </li>
                <? endif; ?>
            </ul>
        </section>
        <div class="tab-content">
            <div class="tab-pane active" id="comm">
                <section class="profile-feed">
                    <?php echo $this->partial(
                        'application/cabinet/my_library_button',
                        ['book' => $book]
                    ); ?>
                    <?php echo $this->partial(
                        'application/index/comments',
                        ['book' => $book]
                    ); ?>
                    <div class="profile-stories">
                        <article class="story">
                            <div class="story-content">
                                <footer>
                                    <script type="text/javascript">
                                        VK.init({
                                            apiId: 6747744,
                                            onlyWidgets: true
                                        });
                                    </script>

                                    <h5 class="text-left">Комментарии с других
                                        ресурсов:</h5>
                                    <div id="vk_comments"
                                         class="margin-button"></div>
                                    <script type="text/javascript">
                                        VK.Widgets.Comments("vk_comments", {
                                            limit: 10,
                                            width: "auto",
                                            attach: "*"
                                        });
                                    </script>
                                    <? if (count($book->getCommentsFaik()) != 0): ?>
                                        <ul class="comments">
                                            <? foreach ($book->getCommentsFaik() as $comentFaik):?>
                                                <?/** @var $comentFaik \Application\Entity\CommentsFaik */?>
                                                <li>
                                                    <div class="user-comment-thumb">
                                                        <img src="<?=IMAGE_URL?>/resize/200/<?= $comentFaik->getFoto(); ?>"
                                                             alt="<?= $comentFaik->getUser(); ?>"
                                                             class="img"
                                                             width="70"/>
                                                    </div>
                                                    <div class="user-comment-content">
                                                        <a href="#"
                                                           class="user-comment-name">
                                                            <?= $comentFaik->getUser(); ?>
                                                        </a>
                                                        <?= strip_tags(
                                                            $comentFaik->getText(),
                                                            '<img><p><br>'
                                                        ); ?>
                                                    </div>
                                                </li>
                                            <? endforeach; ?>
                                        </ul>
                                    <? endif; ?>
                                </footer>
                            </div>
                        </article>
                    </div>
                </section>
            </div>
            <?if(!$problem_avtor):?>
            <div class="tab-pane" id="download">
                <? if (count($book->getFiles()) != 0): ?>
                    Данную книгу  "<?= $book->getName(); ?>" в онлайн вы сможете
                    <b>скачать
                        бесплатно</b> с нашего сайта в следущих по порядку форматах:<br><br>
                    <? foreach ($book->getFiles() as $file): ?>
                        <? /** @var $file \Application\Entity\BookFiles */ ?>
                        <button rel="nofollow" class = "btn btn-success"
                           onclick="download_file.get_files(event, this, '<?= $this->url(
                               'home/download',
                               ['id_book_files' => $file->getIdBookFiles()]
                           ); ?>')"
                        >
                            <?= $file->getType(); ?>
                        </button>
                    <? endforeach; ?>
                <? else: ?>
                    Извините, но у данной книги нет файлов.
                <? endif; ?>
            </div>
            <? endif; ?>
            <? if ($problem_avtor == 0 and count($book->getSoder()) != 0): ?>
                <div class="tab-pane" id="soder">

                    <h3>Оглавление книги <?= $book->getName(); ?></h3>
                    <ul>
                        <? foreach ($book->getSoder() as $soder):?>
                            <?/** @var $soder \Application\Entity\Soder */?>
                            <? $params['content'] = $soder->getAlias(); ?>
                            <li>
                                <a href="<?= $this->url(
                                    $route_similar.'/content',
                                    $params
                                ); ?>"><?= $soder->getName(); ?></a>
                            </li>
                        <? endforeach; ?>
                    </ul>
                </div>
            <? endif; ?>
            <? if ($problem_avtor == 0 and count($similar) != 0): ?>
                <div class="tab-pane" id="similar">

                    <div class="posts-list-4-cols">
                        <? foreach ($similar as $similar): ?>
                            <?/** @var $similar \Application\Entity\Book */?>
                            <?
                            $params_similar = $params;
                            unset($params_similar['content']);
                            $params_similar['book'] = $similar->getAlias();
                            ?>
                            <div class="book_cl">
                                <article class="album">
                                    <header class="bf">
                                        <a href="<?= $this->url(
                                            $route_similar,
                                            $params_similar
                                        ); ?>">
                                                <img class="img-thumbnail"
                                                     src="<?=IMAGE_URL?>/resize/200/<?= $similar->getFoto(); ?>">
                                        </a>
                                    </header>
                                    <section class="album-info">
                                        <h3>
                                            <a href="<?= $this->url(
                                                $route_similar,
                                                $params_similar
                                            ); ?>"><?= $similar->getName(); ?></a>
                                        </h3>
                                    </section>
                                </article>
                            </div>
                        <? endforeach; ?>
                    </div>
                </div>
            <? endif; ?>
        </div>
    </div>
</div>

<?endif;?>