<?php echo $this->comments($book['id'])?>

<textarea id="wiswig-smiles"></textarea>

<div class="row">
    <div class="col-sm-4 margin-button">
        <button  data-book_id="<?=$book['id'];?>" id = "comment-send" type="button" class="btn btn-success">
            Сохранить
        </button>
    </div>
</div>


<link rel="stylesheet" href="/mervick/emojionearea/dist/emojionearea.min.css">
<script type="text/javascript" src="/mervick/emojionearea/dist/emojionearea.min.js"></script>
<script type="text/javascript" src="//vk.com/js/api/openapi.js?121"></script>

<script type="text/javascript">
    VK.init({apiId: 2786799, onlyWidgets: true});
</script>


<div id="vk_comments" class = "margin-button"></div>
<script type="text/javascript">
    VK.Widgets.Comments("vk_comments", {limit: 10, width: "auto", attach: "*"});
</script>
<link rel="stylesheet" href="/assets/js/wysihtml5/bootstrap-wysihtml5.css">
<script src="/assets/js/wysihtml5/wysihtml5-0.4.0pre.min.js"></script>
<script src="/assets/js/wysihtml5/bootstrap-wysihtml5.js"></script>


