<?php $partial = array('layout/breadcrumbs.phtml', 'default') ?>
<?php $this->navigation('NavigationDynamic')->breadcrumbs()->setPartial($partial) ?>
<?php echo $this->navigation('NavigationDynamic')->breadcrumbs()->render() ?>

<h1>Жанры книг бесплатно</h1>
<div class="re">
    <div class="row">
        <div class="col-sm-12">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- b_resize_(all)bookAction -->
            <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-2745956118385780" data-ad-slot="6354762283" data-ad-format="auto"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>
    </div>
</div>
<div class = "text-center">
<?
echo $this->navigation('NavigationDynamic')
	->menu()
	->setPartial('layout/top_menu','default');
?>
</div>
<div>
<?if($menu->getSeoText()):?>
	<blockquote class="blockquote-default">
		<p>
			<small><?=$menu->getSeoText();?></small>
		</p>
	</blockquote>
<?endif;?>
