<?php
/** @var $book \Application\Entity\Book */
?>
<?php $partial = array('layout/breadcrumbs.phtml', 'default') ?>
<?php $this->navigation('NavigationDynamic')->breadcrumbs()->setPartial($partial) ?>
<?php echo $this->navigation('NavigationDynamic')->breadcrumbs()->render() ?>

<?$t = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$params = $t->getParams();
$route = $t->getMatchedRouteName();
?>

<?php echo $this->partial(
    'application/index/sort',
    [
        'route'  => $route,
        'params' => $params,
    ]
);
?>

<div class="posts-list-4-cols">
    <?foreach($paginator as $book):?>
        <?php
            $param = $params;
            $param['s'] = $book->getNS();
            $param['alias_menu'] = $book->getNAliasMenu();
            $param['book'] = $book->getAlias();
            $route_ = 'home/genre/one/book';
            unset($param['paged']);
            echo $this->partial(
                'application/index/book_content',
                [
                        'route' => $route_,
                        'book' => $book,
                        'params' => $param
                ]
            );
        ?>
    <?endforeach;?>
</div>

<div class = "text-center">
    <?
    echo $this->paginationControl(
            null,
            null,
            'pagination_main1'
    );
    ?>
</div>

<?if(isset($params['paged']) and $params['paged'] == ''):?>
    <blockquote class="blockquote-default">
        <h4>Про удобства и возможность бесплатно скачивать книги</h4>
        На сегодня люди настолько привыкли к электронным форматам и интернету, что даже <b>литература</b> приобретается виртуальная. Стоит заметить, что <b>онлайн библиотека</b> - это вовсе не плохо, ведь можно находиться в любом месте и при этом:
        <ul>
            <li><b>скачать книги бесплатно</b>;</li>
            <li><b>читать</b> различные издания;</li>
            <li>выбирать интересующие <b>жанры</b>, не двигаясь с места;</li>
            <li>осуществлять все вышеописанные действия посредством пары легких движений.</li>
        </ul>
        В действительности, благодаря появлению таких форматов, как <b>fb2</b>, <b>txt</b>, <b>rtf</b> и тому подобных, люди этого поколения живут, читают, учатся и обогащаются более удобно. Они не испытывают дискомфорт от пребывания в библиотеке, а также от:
        <ul>
            <li>чтения интересных, но крайне тяжелых книг;</li>
            <li>того, что нужно ехать на другой конец города;</li>
            <li>отсутствия нужного тома, если интересует конкретный <b>автор книги</b>;</li>
            <li>надобности читать редкие издания исключительно в читальном зале.</li>
        </ul>
        Онлайн архив самых различных книг поможет полюбить литературу и открыть ее с новой стороны. Она может быть интересной, полезной и самое главное практичной, ведь открыть электронную книгу можно с любого смартфона, планшета, компьютера и тому подобных устройств. Станьте пользователем нашей электронной библиотеки, и вы поймете то, чего были лишены раньше.
    </blockquote>
<?endif;?>


