<div class="page-error-404">
    <div class="error-symbol">
        <i class="entypo-attention"></i>
    </div>
    <div class="error-text">
        <h4>По данному запросу "<?= $search; ?>", на сайте ничего не найдено. Попробуйте уточнить поиск.</h4>
        <div class="form-group">
            <div class="col-sm-12">
                <form method="GET">
                    <div class="input-group">
										<span class="input-group-btn">
											<input class="btn btn-success" type="submit" value="Поиск">
										</span>
                        <input style="width:100%;" type="text" class="form-control" name="search"
                               value="<?= $search ?>">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
