<?php $partial = array('layout/breadcrumbs.phtml', 'default') ?>
<?php $this->navigation('NavigationDynamic')->breadcrumbs()->setPartial($partial) ?>
<?php echo $this->navigation('NavigationDynamic')->breadcrumbs()->render() ?>

<?$t = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$params = $t->getParams();
$route = $t->getMatchedRouteName();
$params1 = $params;
unset($params['page']);
?>

<?php echo $this->partial(
    'application/index/sort',
    [
        'route'  => $route,
        'params' => $params,
    ]
);
?>
<h1><?=$zhanr->getName();?> читать онлайн</h1>
<?if(count($paginator)):?>
<div class="posts-list-4-cols">
<?foreach($paginator as $book):?>
    <?php
    $param = $params;
    $param['s'] = $book->getNS();
    $param['alias_menu'] = $book->getNAliasMenu();
    $param['book'] = $book->getAlias();
    $route_ = 'home/genre/one/book';
    unset($param['paged']);
    echo $this->partial(
        'application/index/book_content',
        ['route' => $route_, 'book' => $book, 'params' => $param]
    );
    ?>
<?endforeach;?>
</div>
<div class = "text-center">
    <? echo $this->paginationControl(null, null, 'pagination',
        [
            'route' => $route,
            'action'=>$params1['action'],
            's' => $params1['s'],
            'alias_menu' => $params1['alias_menu'],
        ]
    ); ?>
</div>
<?endif;?>


<?if($zhanr->getSeoText() and !$params1['page']):?>
	<blockquote class="blockquote-default">
		<p>
			<small><?=$zhanr->getSeoText();?></small>
		</p>
	</blockquote>
<?endif;?>
