<? $t = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$params = $t->getParams();
$route = $t->getMatchedRouteName();
unset($params['page']);
?>

<div class="alert alert-warning">Данная книга заблокированна правообладателем(либо Роскомнадзор-ом).
        Можно воспользоваться партнерской программой для скачивания
        <a rel="nofollow" target="_blank" href="http://www.litres.ru/pages/biblio_search/?q=<?= $book['name']; ?>&lfrom=294711309">
            <b><?= $book['name']; ?></b> </a>
</div>

<div itemscope itemtype="http://schema.org/Book" itemid="https://www.litres.ru/<?= $_SERVER['REQUEST_URI']; ?>">
    <link itemprop="additionalType" href="http://schema.org/Product"/>
    <h1 itemprop="name"><?= $title; ?></h1>
    <? if (!empty($book['text_small'])): ?>
        <div itemprop="description">
            <?= strip_tags($book['text_small'], '<p>'); ?>
        </div>
    <? endif; ?>
    <div class="profile-env">

        <header class="row">

            <div class="col-sm-2">

                <a href="/templates/newimg/full/<?= $book['foto']; ?>" class="profile-picture">
                    <img itemprop="image" src="/templates/newimg/full/<?= $book['foto']; ?>" class="img-responsive"/>
                </a>

            </div>

            <div class="col-sm-10">

                <ul class="profile-info-sections">
                    <li>
                        <div class="profile-name">
                            <strong>
                                <h2>
                                    <a rel="nofollow" target="_blank" href="http://www.litres.ru/pages/biblio_search/?q=<?= $book['name']; ?>&lfrom=294711309"> <?= $book['name']; ?> скачать</a>
                                </h2>
                                <!-- User statuses available classes "is-online", "is-offline", "is-idle", "is-busy" -->
                            </strong>

                        </div>
                    </li>

                    <li>
                        <div class="profile-stat">
                            <h3><?= $book['visit']; ?></h3>
                            <span>Просмотр(ов)</span>
                        </div>
                    </li>
                </ul>

                <div class="row">
                    <div class="col-sm-12">
                        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                        <!-- b_resize_(all)bookAction -->
                        <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-2745956118385780" data-ad-slot="6354762283" data-ad-format="auto"></ins>
                        <script>
                            (adsbygoogle = window.adsbygoogle || []).push({});
                        </script>
                    </div>
                </div>
            </div>
        </header>
        <section class="profile-info-tabs">

            <div class="row">

                <div class="col-sm-offset-2 col-sm-3">

                    <ul class="user-details">

                        <? if (isset($bookRoute['name']) and !empty($bookRoute['name'])): ?>
                            <li>
                                <i class="entypo-doc-text-inv"></i> Жанр:
                                <a itemprop="genre" href="<?= $this->url('home/genre/one', array(
                                    'alias_menu' => $bookRoute['alias_menu'],
                                    's' => $bookRoute['s']
                                )); ?>"><?= $bookRoute['name']; ?></a>
                            </li>
                        <? endif; ?>

                        <? if ($avtor->count() != 0): ?>
                            <li>

                                <i class="entypo-user"></i> Автор: /
                                <? foreach ($avtor as $v): ?><? $ar = $v->arr; ?>
                                    <a itemprop="author" href="<?= $this->url('home/authors/one', array('alias_menu' => $v->alias)); ?>"><?= $ar['name']; ?></a> /
                                <? endforeach; ?>

                            </li>
                        <? endif; ?>

                        <? if ($serii->count() != 0): ?>
                            <li>
                                <a href="#"> <i class="entypo-layout"></i> Серия:
                                    <? foreach ($serii as $v): ?><? $ar = $v->arr; ?>
                                        <a href="<?= $this->url('home/series/one', array('alias_menu' => $v->alias)); ?>"><?= $ar['name']; ?></a>
                                    <? endforeach; ?>
                                </a>
                            </li>
                        <? endif; ?>
                        <? if ($translit->count() != 0): ?>
                            <li>
                                <i class="entypo-user"></i> Переводчик: / <? foreach ($translit as $v): ?><? $ar = $v->arr; ?>
                                    <a href="<?= $this->url('home/translit/one', array('alias_menu' => $v->alias)); ?>"><?= $ar['name']; ?></a> /
                                <? endforeach; ?>
                            </li>
                        <? endif; ?>
                        <? if ($book['kol_str']): ?>
                            <li>
                                <i class="entypo-pencil"></i> Количество страниц:
                                <span itemprop="numberOfPages"><?= $book['kol_str']; ?></span>
                            </li>
                        <? endif; ?>

                        <? if ($book['lang']): ?>
                            <li>
                                <i class="entypo-language"></i> Язык книги:
                                <span itemprop="inLanguage"><?= $book['lang']; ?></span>
                            </li>
                        <? endif; ?>

                        <? if ($book['year']): ?>
                            <li>
                                <i class="entypo-calendar"></i> Год:
                                <span itemprop="copyrightYear"><?= $book['year']; ?></span>
                            </li>
                        <? endif; ?>

                        <? if ($book['city']): ?>
                            <li>
                                <i class="entypo-globe"></i> Город печати: <?= $book['city']; ?>
                            </li>
                        <? endif; ?>
                    </ul>

                </div>

                <div class="col-sm-offset-1 col-sm-6">
                    <div class="profile-buttons">
                        <script type="text/javascript" src="/js/es5-shims.min.js" charset="utf-8"></script>
                        <script type="text/javascript" src="/js/share.js" charset="utf-8"></script>
                        <div class="ya-share2" data-services="vkontakte,facebook,odnoklassniki,moimir,gplus,twitter,linkedin,lj,viber,whatsapp"></div>
                    </div>

                </div>

            </div>
            <? if ($similar->count() != 0): ?>
                <ul class="nav nav-tabs tabs-book">
                    <li class="active"><a data-toggle="tab" href="#similar">Схожие книги</a></li>
                </ul>
            <? endif; ?>
        </section>

        <? if ($similar->count() != 0): ?>
            <div class="tab-content">
                <div class="tab-pane" id="similar">
                    <div class="posts-list-4-cols">
                        <? foreach ($similar as $v1): ?><?
                            $params_similar = $params;
                            unset($params_similar['content']);
                            $params_similar['book'] = $v1->book_alias;
                            ?>

                            <div class="book_cl">
                                <article class="album">
                                    <header class="bf">
                                        <a href="<?= $this->url('home/genre/one/book', $params_similar); ?>">
                                            <img class="img-thumbnail" src="/templates/newimg/small/<?= $v1->foto; ?>">
                                        </a>
                                    </header>
                                    <section class="album-info">
                                        <h3>
                                            <a href="<?= $this->url('home/genre/one/book', $params_similar); ?>"><?= $v1->book_name; ?></a>
                                        </h3>
                                    </section>
                                </article>
                            </div>

                        <? endforeach; ?>
                    </div>
                </div>
            </div>
        <? endif; ?>
    </div>
