<div class = "re">
<div class="row">
	<div class="col-sm-12">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- b_resize_(all)bookAction -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2745956118385780"
     data-ad-slot="6354762283"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
</div>
	</div>