<?php  $partial = array('layout/breadcrumbs.phtml', 'default') ?>
<?php $this->navigation('NavigationDynamic')->breadcrumbs()->setPartial($partial) ?>
<?php  echo $this->navigation('NavigationDynamic')->breadcrumbs()->render() ?>
<h1><?=$title;?></h1>
<?=$this->permission()->zhanrOld($book->getMenu()->getOld());?>
<div>
    <?php echo $this->partial('application/index/stars',
        [
                'id_book' => $book->getId(),
                'aver_value' => $book->getStars(),
                'count_stars' => $book->getCountStars()
        ]
    );?>
</div>

<?if(count($paginator)):?>
<div class = "book_" data-id = "<?=$book->getId();?>">
    <?foreach($paginator as $v):?>
        <?=$this->ad()->content($v->getTextImgServer());?>
    <?endforeach;?>
</div>
<div class = "text-center">
    <?
    echo $this->paginationControl(
        null,
        null,
        'pagination_book',
        [
            'route'      => $route,
            'action'     => $params['action'],
            'alias_menu' => $params['alias_menu'],
            'book'       => $params['book'],
            's'          => ($params['s'])??null,
        ]
    ); ?>
</div>
<?endif;?>

<div class="modal fade" id="modal-7">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-hidden="true">&times;
                </button>
                <h4 class="modal-title">Dynamic Content</h4></div>
            <div class="modal-body">
                Content is loading...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal">Закрыть
                </button>
            </div>
        </div>
    </div>
</div>
<script>


    $(document).ready(function () {
        $('.notes_go').on('click', function(){
            var link = $(this).data('notes-id');
            var book_id = $('.book_').data('id');
            $('#modal-7').modal('show', {backdrop: 'static'});
            $.ajax(
                {
                    url:'/notes/',
                    data:{link:link,book_id:book_id},
                    type:"POST",
                    dataType:"json",
                    success: function (json) {
                        if(json.err == 0) {
                            jQuery('#modal-7 .modal-title').html(json.title);
                            jQuery('#modal-7 .modal-body').html(json.text);
                        }
                        else{
                            toastr.error(json.text, 'Ошибка',
                                {
                                    "tapToDismiss": false,
                                    "closeButton": true

                                }
                            )
                        }
                    }
                }
            )
        });
    })

</script>