<div class="col-md-12">
    <div class="panel panel-primary" data-collapsed="<?= $where['collapsed']; ?>">
        <div class="panel-heading">
            <div class="panel-title">
                Пользовательский поиск
            </div>
            <div class="panel-options">
                <a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a>
                <a href="#" data-rel="close"><i class="entypo-cancel"></i></a>
            </div>
        </div>
        <div class="panel-body">
            <form class="search" method="GET" action="/search/">
                <div class="row">
                    <div class="col-md-12">
                        <? foreach ($where['params'] as $k => $v): ?>
                            <div class="col-sm-4 m-top-sm-5">
                                <div class="input-group">
                                    <span class="input-group-addon"><?= $v['name'] ?></span>
                                    <input value="<?= htmlspecialchars($v['value']); ?>" name="<?= $k; ?>" type="text"
                                           class="form-control" placeholder="">
                                </div>
                            </div>
                        <? endforeach; ?>
                    </div>
                    <div class="col-md-12">
                        <div class="col-sm-3 m-top-sm-5">
                            <input class="btn btn-success" type="submit" value="Поиск в библиотеке">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<link href="/autocomplite/jquery-ui.css" rel="stylesheet">
<script src="/autocomplite/external/jquery/jquery.js"></script>
<script src="/autocomplite/jquery-ui.min.js"></script>
<script>
    $(function () {
        function log(message) {
            $("<div>").text(message).prependTo("#log");
            $("#log").scrollTop(0);
        }

        $("form.search input[type=text]:not(.autocomp)").autocomplete({
            source: function (request, response) {
                name = this.element.attr('name');
                $.ajax({
                    url: "/ajaxsearch/",
                    dataType: "json",
                    data: {
                        term: {
                            name: name,
                            value: request.term,
                        }
                    },
                    success: function (data) {
                        response(data);
                    }
                });
            },
            minLength: 2,
            select: function (event, ui) {
                log("Selected: " + ui.item.value + " aka " + ui.item.id);
            }
        });
    });
</script>