<?php $partial = array('layout/breadcrumbs.phtml', 'default') ?>
<?php $this->navigation('NavigationDynamic')->breadcrumbs()->setPartial($partial) ?>
<?php echo $this->navigation('NavigationDynamic')->breadcrumbs()->render() ?>

<?$t = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$params = $t->getParams();
$route = $t->getMatchedRouteName();
?>

<?php echo $this->partial(
    'application/index/sort',
    [
        'route'  => $route,
        'params' => $params,
    ]
);
?>

<?if($book and count($book) > 0):?>

<div class="posts-list-4-cols">
    <?foreach($book as $k => $v):?>
        <?php
        try {
        $param = $params;
        $param['s'] =  $v->n_s;
        $param['alias_menu'] =  $v->n_alias_menu;
        $param['book'] =  $v->alias;
        $route_ = 'home/genre/one/book';
        echo $this->partial('application/index/book_content', ['route' => $route_, 'v' => $v, 'params' => $param]);
        }
        catch (Exception $e){
            syslog(
                LOG_ERR,
                json_encode(
                    [
                        'type'    => 'error_mzhanr',
                        'book_id' => $v->id,
                    ]
                )
            );
        }
        ?>

    <?endforeach;?>
</div>

<div class = "text-center">
    <?
    unset($params['book']);

    echo $this->paginationControl($pag, 'Sliding', 'pagination_main',
        array(
            'route' => $route,
            'action'=>$params['action'],
        ));
    ?>
</div>


    <?else:?>

    <div class="alert alert-info">
        <strong>Поиск: </strong> Ничего не найдено.
    </div>

<?endif;?>

