<?$t = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$params = $t->getParams();
$route = $t->getMatchedRouteName();
?>


<section class="search-results-env">

    <div class="row">
        <div class="col-md-12">
 

            <div class="search-results-panes">

                <div class="search-results-pane active" id="pages">

                    <?if($book):?>
                        <ul class="search-results">
                            <?foreach($book as $v):?>

                                <li class="search-result">
                                    <div class="sr-inner">
									
						 
                                        <h4>
                                            <a href="<?=$this->url('home/genre/one/book', array('s' => $v->n_s, 'alias_menu' => $v->n_alias_menu, 'book'=>$v->alias));?>"><?=$v->name;?></a>
                                        </h4>

                                        <div class="row">
                                            <div class="col-sm-2">
                                                <img  class="img-thumbnail" src="/templates/newimg/small/<?=$v->foto;?>">
                                            </div> 

                                            <div class="col-sm-8">
                                                <?=$v->text_small;?>
                                            </div>
											
											 <div class="col-sm-2">
                                                Просмотров: <?=$v->visit;?>
                                            </div>
											
                                        </div>

                                    </div>
                                </li>
                            <?endforeach;?>
                        </ul>
                    <?endif;?>
                </div>

            </div>



        </div>
    </div>

</section>