<?php  $partial = array('layout/breadcrumbs.phtml', 'default') ?>
<?php $this->navigation('NavigationDynamic')->breadcrumbs()->setPartial($partial) ?>
<?php echo $this->navigation('NavigationDynamic')->breadcrumbs()->render() ?>
<?
unset($params['page_author']);
?>
<h1><?=$title;?></h1>
<div class="re">
    <div class="row">
        <div class="col-sm-12">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- b_resize_(all)bookAction -->
            <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-2745956118385780" data-ad-slot="6354762283" data-ad-format="auto"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>
    </div>
</div>
<?if(count($paginator)):?>
<div class="posts-list-4-cols">
<?foreach($paginator as $book):?>
    <?php
    $param = $params;
    $param['book'] = $book->getAlias();
    $route_ = 'home/series/one/book';
    echo $this->partial('application/index/book_content',
        ['route' => $route_,
         'book' => $book,
         'params' => $param
        ]
    );
    ?>
<?endforeach;?>
</div>
<?endif;?>
<div class = "text-center">
<?
echo $this->paginationControl(
    null,
    null,
    'pagination_series_one',
    [
        'route'      => $route,
        'action'     => $params['action'],
        'alias_menu' => $params['alias_menu'],
    ]
);
?>
</div>
