<?php  $partial = array('layout/breadcrumbs.phtml', 'default') ?>
<?php $this->navigation('NavigationDynamic')->breadcrumbs()->setPartial($partial) ?>
<?php echo $this->navigation('NavigationDynamic')->breadcrumbs()->render() ?>
<?
unset($params['page']);
?>
<h1>Серии</h1>
<?if(count($paginator)):?>
<div class="posts-list-4-cols">
<?foreach($paginator as $serii):?>
		<?$params['alias_menu'] = $serii->getAlias();?>
		<a  href="<?=$this->url('home/series/one', $params);?>">
            <?=$serii->getName();?>
        </a>
<?endforeach;?>
</div>
<div class = "text-center">
    <?
    echo $this->paginationControl(
        null,
        null,
        'pagination_authors',
        [
            'route'  => $route,
            'action' => $params['action'],
        ]
    );
    ?>
</div>
<?endif;?>
<?if(!empty($menu->getSeoText())):?>
	<blockquote class="blockquote-default">
		<p>
			<small><?=$menu->getSeoText();?></small>
		</p>
	</blockquote>
<?endif;?>