<?php  $partial = array('layout/breadcrumbs.phtml', 'default') ?>
<?php $this->navigation('NavigationDynamic')->breadcrumbs()->setPartial($partial) ?>
<?php echo $this->navigation('NavigationDynamic')->breadcrumbs()->render() ?>

<?$t = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$params = $t->getParams();
$route = $t->getMatchedRouteName();
unset($params['page_author']);
?>
<h1><?=$title;?></h1>
<?if(count($paginator)):?>
<div class="posts-list-4-cols">
<?foreach($paginator as $book):?>
    <?php
    $param = $params;
    $param['book'] = $book->getAlias();
    $route_ = 'home/series/one/book';
    echo $this->partial('application/index/book_content',
        ['route' => $route_,
         'book' => $book,
         'params' => $param
        ]
    );
    ?>
<?endforeach;?>
</div>
<?endif;?>
<div class = "text-center">
<?
echo $this->paginationControl(
    null,
    null,
    'pagination_series_one',
    [
        'route'      => $route,
        'action'     => $params['action'],
        'alias_menu' => $params['alias_menu'],
    ]
);
?>
</div>
