<?php $partial = array('layout/breadcrumbs.phtml', 'default') ?>
<?php $this->navigation('NavigationDynamic')->breadcrumbs()->setPartial($partial) ?>
<?php echo $this->navigation('NavigationDynamic')->breadcrumbs()->render() ?>

<?$t = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$params = $t->getParams();
$route = $t->getMatchedRouteName();
unset($params['page']);
?>

<h1>Карта сайта</h1>

 
<?php
echo $this->navigation("NavigationDynamic")
	->menu()
?>
<script language="javascript">
    $( document ).ready(function() {
        $('li>a').each(function(){
            if ($(this).html() == $(this).closest('ul').siblings('a').html()) {
                $(this).closest('li').remove();
            }
        });
    });
</script>
