<?php $partial = array('layout/breadcrumbs.phtml', 'default') ?>
<?php $this->navigation('NavigationDynamic')->breadcrumbs()->setPartial(
    $partial
) ?>
<?php echo $this->navigation('NavigationDynamic')->breadcrumbs()->render() ?>
<?
unset($params['page']);
?>
<h1>Переводчики</h1>
<?if(count($paginator)):?>
<div class="posts-list-4-cols">
    <? foreach ($paginator as $translit): ?>
        <? $params['alias_menu'] = $translit->getAlias(); ?>
        <a href="<?= $this->url(
            'home/translit/one',
            $params
        ); ?>"><?= $translit->getName(); ?>
        </a>
    <? endforeach; ?>
</div>
<div class="text-center">
    <?
    echo $this->paginationControl(
        null,
        null,
        'pagination_authors',
        [
            'route'  => $route,
            'action' => $params['action'],
        ]
    ); ?>
</div>
<?endif;?>
<? if ($menu->getSeoText()): ?>
    <blockquote class="blockquote-default">
        <p>
            <small><?= $menu->getSeoText(); ?></small>
        </p>
    </blockquote>
<? endif; ?>