<style>
    h1{
        font-size: 16px;
        color: #373e4a;
        text-align: center;
        background: #d8e8ff;
        padding: 10px;
        border-radius: 5px 5px 0 0;
    }
    h2{
        font-size: 14px;
        color: #373e4a;
        text-align: center;
    }
    .content-body{
    }

    .book{
        padding: 10px;
        border-bottom: 1px solid #ccc;
        background: #fbfbfb;
    }

    table td{
        vertical-align: top;
    }
    ul {
        list-style: none;
    }
    ul li{
        list-style: none;
        margin: 0;
        padding: 0;
    }

    img{
        padding: 5px;
        border: 1px solid #ccc;
    }

    h2 a{
        text-decoration: underline;
        color: #3f72a2;
    }

    h2 a:hover{
        text-decoration: underline;
    }

    a{
        text-decoration: underline;
        color: #3f72a2;
    }

    a:hover{
        text-decoration: underline;
    }

    .td2{
        width: 80%;
    }

    .footer{
        text-align: center;
        padding: 10px;
        background: #ececec;
        border-radius: 0 0 5px 5px;
    }
</style>
<div class = "content-body">
<h1>Популярные книги на BOOKLOT.RU</h1>
    <?foreach ($books as $book):?>
    <div class = "book">
        <?
        $param['s'] = $book->getNS();
        $param['alias_menu'] = $book->getNAliasMenu();
        $param['book'] = $book->getAlias();
        $route_ = 'home/genre/one/book';
        ?>
        <h2 class = "text-center"><a href="<?=$url;?><?= $this->url($route_, $param); ?>">
                <?=$book->getName();?>
            </a>
        </h2>
        <table>
            <tr>
                <td class="td1">
                    <img  class="img-thumbnail" alt="Cinque Terre" src="https://www.image.booklot.ru/resize/200/<?= $book->getFoto(); ?>">
                </td>
                <td class="td2">
                    <ul class="list-group list-group-flush">
                        <?
                        $params['alias_menu'] = $book->getNAliasMenu();
                        $params['action'] = 'one_genre';
                        $params['s'] = $book->getNS();
                        ?>
                        <li class="list-group-item">
                            <b>Жанр:</b>
                            <a href="<?=$url;?><?= $this->url(
                                'home/genre/one',
                                $params
                            ); ?>"><?= $book->getNameZhanr(); ?></a>
                        </li>
                        <? if(count($book->getAvtor())):?>
                            <li class="list-group-item"><b>Автор:</b>
                                <?foreach($book->getAvtor() as $avtor):?>
                                    <a href = "<?=$url;?><?=$this->url(
                                        'home/authors/one',
                                        [
                                            'alias_menu' => $avtor->getAlias()
                                        ]
                                    );?>"><?=$avtor->getName();?></a> /
                                <?endforeach;?>
                            </li>
                        <?endif;?>
                        <? if(count($book->getSerii())):?>
                            <li  class="list-group-item"><b>Серия:</b>
                                <?foreach($book->getSerii() as $serii):?>
                                    <a href = "<?=$url;?><?=$this->url(
                                        'home/series/one',
                                        [
                                            'alias_menu' => $serii->getAlias()
                                        ]
                                    );?>"><?=$serii->getName();?></a> /
                                <?endforeach;?>
                            </li>
                        <?endif;?>
                        <li>Страниц: <span><?= $book->getKolStr(); ?></span></li>
                        <li>Язык: <span><?= $book->getLang(); ?></span></li>
                        <?if(!empty($book->getYear())):?>
                            <li>Год: <span><?= $book->getYear(); ?></span></li>
                        <?endif;?>
                        <? if ($book->getTypeFiles()): ?>
                            <li>Файлы: <span><?= $book->getTypeFiles(); ?></span></li>
                        <? endif; ?>
                    </ul>
                </td>
            </tr>
        </table>
    </div>
    <?endforeach;?>
</div>
<div class = "footer">
    Спасибо что читаете литературу на сайте <a href = "https://www.booklot.ru/">www.booklot.ru</a>
</div>