<link rel="stylesheet" type="text/css" href="/css/bootstrap.css">
<link rel="stylesheet" type="text/css" href="/css/mail.css">

<div class = "content-body">
<h1>Последние добавленые книги</h1>

    <div class = "book">
        <h2 class = "text-center">Не грози южному централу</h2>
        <div class="row">
            <div class = "col-sm-4">
                <img  class="img-thumbnail" alt="Cinque Terre" src="https://www.image.booklot.ru/resize/200/2d702d5e5881ca27c473fc95199d59b6.jpeg">
            </div>
            <div class = "col-sm-8">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><b>Автор:</b> <a href="#">тетрис</a></li>
                    <li class="list-group-item"><b>Жанр:</b> <a href="#">тетрис</a></li>
                    <li class="list-group-item"><b>Автор:</b> <a href="#">тетрис</a></li>
                    <li class="list-group-item"><b>Автор:</b> <a href="#">тетрис</a></li>
                    <li class="list-group-item"><b>Автор:</b> <a href="#">тетрис</a></li>
                </ul>
            </div>
        </div>
    </div>

</div>